In [1]:
import pandas as pd
import numpy as np

<h1 style="color:red; text-align:center">le nettoyage de fichier useMobility.xlsx</h1>

In [2]:
#df=pd.read_xlsx('Base Transport stage 1.xlsx')
df = pd.read_excel('userMobility.xlsx')

In [3]:
print(df)

    username                 display_name
0        781                 CHEBBI AHMED
1      13110             AGUERBAOUI YAHIA
2      13095               GHARBI MAROUEN
3      13006              GUITOUNI HASSEN
4        716                 BELAAZI FEDI
..       ...                          ...
374     1472  Ghazi khalfallah / DUBETANT
375     1464          ARBI CHERIF - Perso
376   TRP328              MORTADHA AABIDI
377   101341               OUSSAMA KILANI
378     1456               BEN SAID SAMIR

[379 rows x 2 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 379 entries, 0 to 378
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   username      379 non-null    object
 1   display_name  379 non-null    object
dtypes: object(2)
memory usage: 6.1+ KB

In [5]:
print(len(df))

379

In [6]:
print(df.shape)

(379, 2)

In [7]:
df.isnull().sum()

username        0
display_name    0
dtype: int64

In [8]:
df['username'].duplicated().sum()

np.int64(0)

In [9]:
df[df.duplicated()]

Empty DataFrame
Columns: [username, display_name]
Index: []

In [10]:
print('test')

test

In [11]:
pip install python-calamine

Requirement already satisfied: python-calamine in c:\users\nourg\anaconda3\lib\site-packages (0.8.2)
Note: you may need to restart the kernel to use updated packages.

In [12]:
import os
print(os.path.getsize('mobility.xlsx') / (1024*1024), "MB")

44.824416160583496 MB

<h1 style="color:red; text-align:center">le nettoyage de fichier TMS.csv</h1>

In [13]:
dfT = pd.read_csv('TMS.csv', sep=';', encoding='latin-1')

C:\Users\nourg\AppData\Local\Temp\ipykernel_7748\882306.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  dfT = pd.read_csv('TMS.csv', sep=';', encoding='latin-1')

In [14]:
dfT.head()

,ARTCODE,CDATE,LIVRAISON,VOYCLE,PLALIB,PLAMOTI,SALNOM,PLACHA1I,TIECODE,VOYDTD,...,PLAKM2,Deposant,OTSNUMBDX,Type_TRANSPORT,CAPACITE,SITE_CHAUFFEUR,Type_Tourne,Type de marchandise,Temprature,SITE
0,T004,2026-02-20 00:00:00.000,9004,8289736,TRANSPORT AMBIANT,9471TU205,BEN BRAHIM ABDELKADER,418,CRISTAL,2026-02-23 00:00:00.000,...,0,EXTERNE,DIV0013362,LT,0.0,BAR,Facture,AMBIANT,Temprature AMBIANT,BAR
1,T004,2026-02-20 00:00:00.000,BKS042-AD1,8289956,TRANSPORT AMBIANT,527TU174,TALEB SAMI,428,CSG,2026-02-21 00:00:00.000,...,72,GIAS,CD2602-PGF08443,LT,3.0,GAF,Facture,AMBIANT,Temprature AMBIANT,GAF
2,T004,2026-02-20 00:00:00.000,BKS051-AD1,8289956,TRANSPORT AMBIANT,527TU174,TALEB SAMI,428,CSG,2026-02-21 00:00:00.000,...,123,GIAS,CD2602-PGF08383,LT,3.0,GAF,Facture,AMBIANT,Temprature AMBIANT,GAF
3,T004,2026-02-09 00:00:00.000,STU006-A90,8235406,TRANSPORT AMBIANT,8564TU232,BEL HASSEN MOEZ,411,DGC,2026-02-10 00:00:00.000,...,0,GIAS,CD2602-CBR04738,LT,10.0,BAR,Facture,AMBIANT,Temprature AMBIANT,BAR
4,T004,2026-02-09 00:00:00.000,STU006-A90,8235406,TRANSPORT AMBIANT,8564TU232,BEL HASSEN MOEZ,411,DGC,2026-02-10 00:00:00.000,...,0,GIAS,CD2602-CBR04807,LT,10.0,BAR,Facture,AMBIANT,Temprature AMBIANT,BAR

In [15]:
print(dfT.shape)

(494087, 26)

In [16]:
test = False
for i in range(len(dfT)):
    try:
        if dfT.loc[i, 'PLACHA1I'] == 418:
            test = True
            break
    except:
        test = False
        continue

print(test)

False

In [17]:
dfT.duplicated().sum()

np.int64(654)

In [18]:
dfT[dfT.duplicated()]

,ARTCODE,CDATE,LIVRAISON,VOYCLE,PLALIB,PLAMOTI,SALNOM,PLACHA1I,TIECODE,VOYDTD,...,PLAKM2,Deposant,OTSNUMBDX,Type_TRANSPORT,CAPACITE,SITE_CHAUFFEUR,Type_Tourne,Type de marchandise,Temprature,SITE
149350,T011,2026-01-07 00:00:00.000,1155,8108502,TRANSPORT FRUIT,9134TU135,CHIHI HELMI,412361,AZI,2026-01-11 00:00:00.000,...,0,THO,"2,60105E+12",LT,7.0,NAS,Facture,FRUIT,Temprature FRAIS,NAS
149357,T011,2026-01-07 00:00:00.000,1192,8108458,TRANSPORT FRUIT,9916TU215,RAYEN ABDELKADER,100537,AZI,2026-01-10 00:00:00.000,...,0,THO,"2,60105E+12",LT,10.0,NAS,Facture,FRUIT,Temprature FRAIS,NAS
150263,T011,2026-01-14 00:00:00.000,1165,8133738,TRANSPORT FRUIT,5084TU198,AHMED BOUGHRARA,412659,AZI,2026-01-16 00:00:00.000,...,20,THO,"2,60105E+12",LT,10.0,NAS,Facture,FRUIT,Temprature FRAIS,NAS
150985,T011,2026-01-22 00:00:00.000,1222,8160929,TRANSPORT FRUIT,6064TU197,AMRI SKANDER,1071,AZI,2026-01-27 00:00:00.000,...,8,THO,"2,60105E+12",LT,10.0,NAS,Facture,FRUIT,Temprature FRAIS,NAS
168204,T011,2026-02-04 00:00:00.000,1155,8214081,TRANSPORT FRUIT,9916TU215,RAYEN ABDELKADER,100537,AZI,2026-02-08 00:00:00.000,...,0,THO,"2,60205E+12",LT,10.0,NAS,Facture,FRUIT,Temprature FRAIS,NAS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488510,T011,2026-05-17 00:00:00.000,1079,8643138,TRANSPORT FRUIT,6068TU197,BELGACEM BELGHITH,13135,AZI,2026-05-23 00:00:00.000,...,11,THO,"2,60505E+12",TRP INT,10.0,BKS,Facture,FRUIT,Temprature FRAIS,NAS
488511,T011,2026-05-17 00:00:00.000,1192,8643138,TRANSPORT FRUIT,6068TU197,BELGACEM BELGHITH,13135,AZI,2026-05-23 00:00:00.000,...,0,THO,"2,60505E+12",TRP INT,10.0,BKS,Facture,FRUIT,Temprature FRAIS,NAS
490717,T011,2026-02-14 00:00:00.000,1036,8258550,TRANSPORT FRUIT,718TU193,DRIDI LASSAD,13145,AZI,2026-02-14 00:00:00.000,...,39,THO,"2,60205E+12",TRP INT,10.0,BKS,Facture,FRUIT,Temprature FRAIS,NAS
493114,T011,2026-05-16 00:00:00.000,1335,8640558,TRANSPORT FRUIT,5083TU175,ATEF TWAHNI,13154,AZI,2026-05-23 00:00:00.000,...,26,THO,"2,60505E+12",TRP INT,10.0,BKS,Facture,FRUIT,Temprature FRAIS,NAS
493115,T011,2026-05-16 00:00:00.000,1335,8640558,TRANSPORT FRUIT,5083TU175,ATEF TWAHNI,13154,AZI,2026-05-23 00:00:00.000,...,26,THO,"2,60505E+12",TRP INT,10.0,BKS,Facture,FRUIT,Temprature FRAIS,NAS

In [19]:
dfT.isnull().sum()

ARTCODE                 3793
CDATE                      0
LIVRAISON                966
VOYCLE                     0
PLALIB                  3793
PLAMOTI                    0
SALNOM                     0
PLACHA1I                   0
TIECODE                    0
VOYDTD                     0
VOYHRD                     0
VOYDTF                     0
VOYHRF                     0
VOYPAL                     0
SITESALARIE              721
SITECAMION                 0
PLAKM2                     0
Deposant                   0
OTSNUMBDX               3059
Type_TRANSPORT             0
CAPACITE               20238
SITE_CHAUFFEUR           721
Type_Tourne               0
Type de marchandise        0
Temprature                0
SITE                       0
dtype: int64

In [20]:
resNull=dfT.isnull().sum()
resNull_percent = (resNull/len(dfT))*100
res = pd.DataFrame({
    'nombre_null':resNull,
    'pourcentage_Null':resNull_percent
})
print(res[res['nombre_null']>0])

                nombre_null  pourcentage_Null
ARTCODE                3793          0.767679
LIVRAISON               966          0.195512
PLALIB                 3793          0.767679
SITESALARIE             721          0.145926
OTSNUMBDX              3059          0.619122
CAPACITE              20238          4.096040
SITE_CHAUFFEUR          721          0.145926

In [21]:
#la grande problematique est la capacite car elle a la grande la proportion de valeurs manquantes par rapport au nombre total de lignes 
print(dfT['CAPACITE'].dtype)

float64

In [22]:
print(dfT['CAPACITE'].describe())

count    473849.000000
mean         31.567622
std          98.699354
min           0.000000
25%          10.000000
50%          10.000000
75%          18.000000
max         550.000000
Name: CAPACITE, dtype: float64

In [23]:
print((dfT['CAPACITE'] == 0).sum())

16387

In [24]:
print(dfT['CAPACITE'].value_counts().sort_index())

CAPACITE
0.0       16387
3.0       21206
6.0       27473
7.0        6757
8.0       13189
9.0         660
10.0     234503
12.0        140
13.0       1003
14.0       2028
15.0       8754
16.0       2938
17.0      11287
18.0      11293
20.0      93359
23.0       1506
30.0        336
32.0       1938
33.0         91
350.0      4090
550.0     14911
Name: count, dtype: int64

In [25]:
#remplacer les valeur manquante seulement(nan)
mediane =dfT.loc[dfT['CAPACITE']!=0 ,'CAPACITE'].median()
dfT['CAPACITE'] = dfT['CAPACITE'].fillna(mediane)

In [26]:
dfT.isnull().sum()

ARTCODE                3793
CDATE                     0
LIVRAISON               966
VOYCLE                    0
PLALIB                 3793
PLAMOTI                   0
SALNOM                    0
PLACHA1I                  0
TIECODE                   0
VOYDTD                    0
VOYHRD                    0
VOYDTF                    0
VOYHRF                    0
VOYPAL                    0
SITESALARIE             721
SITECAMION                0
PLAKM2                    0
Deposant                  0
OTSNUMBDX              3059
Type_TRANSPORT            0
CAPACITE                  0
SITE_CHAUFFEUR          721
Type_Tourne              0
Type de marchandise       0
Temprature               0
SITE                      0
dtype: int64

In [27]:
print(dfT['CAPACITE'].head(50))

0      0.0
1      3.0
2      3.0
3     10.0
4     10.0
5     10.0
6     10.0
7     10.0
8     10.0
9      6.0
10    10.0
11     6.0
12     6.0
13     3.0
14    10.0
15    10.0
16    10.0
17    10.0
18    10.0
19    10.0
20    17.0
21    20.0
22    10.0
23    10.0
24    10.0
25    20.0
26    20.0
27    20.0
28    10.0
29    10.0
30    20.0
31    10.0
32    10.0
33    10.0
34    10.0
35    18.0
36    20.0
37    10.0
38    10.0
39    20.0
40    10.0
41    20.0
42    20.0
43    10.0
44    20.0
45    10.0
46    20.0
47    20.0
48    32.0
49    10.0
Name: CAPACITE, dtype: float64

In [28]:
colonnes = [
    'ARTCODE',
    'LIVRAISON',
    'PLALIB',
    'SITESALARIE',
    'OTSNUMBDX',
    'SITE_CHAUFFEUR'
]

for col in colonnes:
    print("\n==============================")
    print("COLONNE :", col)
    print("==============================")
    print(dfT[col].value_counts(dropna=False).head(15))

==============================
COLONNE : ARTCODE
==============================
ARTCODE
T004    198574
T007     91046
T003     61815
T017     47438
T008     32915
T011     28019
T019     10044
T033      6097
NaN       3793
T002      3645
T015      1931
T032      1657
T013      1558
T027      1136
T024      1103
Name: count, dtype: int64

==============================
COLONNE : LIVRAISON
==============================
LIVRAISON
QUAI-MHA     7705
QUAI-TPK     4200
QUAI-BHF     2432
9007         2173
9005         1899
9002         1794
903          1450
9001         1450
PERSONNEL    1102
MGH          1019
NaN           966
1189          922
1602          869
1460          857
1096          852
Name: count, dtype: int64

==============================
COLONNE : PLALIB
==============================
PLALIB
TRANSPORT AMBIANT                198574
TRANSPORT DU FRAIS // 4¡C         91046
TRANSPORT CONTRLé // 12¡C        61815
TRANSPORT SPOT                    47438
TRANSPORT SURGELE // -22¡C        32915
TRANSPORT FRUIT                   28019
TRANSPORT RETOUR EMBALLAGE        10044
TRANSPORT INTER DEPOT ANNEXE       6097
NaN                                3793
TRANSPORT FRAIS GRP // 4¡C         3645
TRANSFERT INTER DEPOT FACTURE      1931
TRANSPORT MISSION PARC             1657
TRANSPORT RETOUR                   1558
TRANSPORT PERSONNEL                1136
REPARATION-MECA-ELECT-PNEUM        1103
Name: count, dtype: int64

==============================
COLONNE : SITESALARIE
==============================
SITESALARIE
BAR     131234
SAL      98964
BKS      84070
9901     40261
GAB      32866
SFX      32006
MGH      30698
TUN      25103
JER       5617
BSL       4891
GAS       4397
BIZ       2857
NaN        721
NAS        402
Name: count, dtype: int64

==============================
COLONNE : OTSNUMBDX
==============================
OTSNUMBDX
2,60705E+12    4439
2,60405E+12    4234
2,60605E+12    3997
2,60105E+12    3773
2,60205E+12    3744
2,60305E+12    3707
2,60505E+12    3626
NaN            3059
2,60805E+12     547
2,51205E+12     200
2117168           3
2162836           3
2122046           3
2117458           3
2122356           3
Name: count, dtype: int64

==============================
COLONNE : SITE_CHAUFFEUR
==============================
SITE_CHAUFFEUR
BAR    131234
SAL     98964
BKS     84070
NAS     40663
GAB     32866
SFX     32006
MGH     30698
MHA     25103
JER      5617
BSL      4891
GAF      4397
BIZ      2857
NaN       721
Name: count, dtype: int64

In [29]:
dfT['ARTCODE'] = dfT['ARTCODE'].fillna('INCONNU')

In [30]:
dfT.isnull().sum()

ARTCODE                   0
CDATE                     0
LIVRAISON               966
VOYCLE                    0
PLALIB                 3793
PLAMOTI                   0
SALNOM                    0
PLACHA1I                  0
TIECODE                   0
VOYDTD                    0
VOYHRD                    0
VOYDTF                    0
VOYHRF                    0
VOYPAL                    0
SITESALARIE             721
SITECAMION                0
PLAKM2                    0
Deposant                  0
OTSNUMBDX              3059
Type_TRANSPORT            0
CAPACITE                  0
SITE_CHAUFFEUR          721
Type_Tourne              0
Type de marchandise       0
Temprature               0
SITE                      0
dtype: int64

In [31]:
dfT['PLALIB'] = dfT['PLALIB'].fillna('INCONNU')

In [32]:
dfT.isnull().sum()

ARTCODE                   0
CDATE                     0
LIVRAISON               966
VOYCLE                    0
PLALIB                    0
PLAMOTI                   0
SALNOM                    0
PLACHA1I                  0
TIECODE                   0
VOYDTD                    0
VOYHRD                    0
VOYDTF                    0
VOYHRF                    0
VOYPAL                    0
SITESALARIE             721
SITECAMION                0
PLAKM2                    0
Deposant                  0
OTSNUMBDX              3059
Type_TRANSPORT            0
CAPACITE                  0
SITE_CHAUFFEUR          721
Type_Tourne              0
Type de marchandise       0
Temprature               0
SITE                      0
dtype: int64

In [33]:
dfT['SITESALARIE'] = dfT['SITESALARIE'].fillna('INCONNU')

In [34]:
dfT['SITE_CHAUFFEUR'] = dfT['SITE_CHAUFFEUR'].fillna('INCONNU')

In [35]:
dfT['LIVRAISON_MANQUANTE'] = dfT['LIVRAISON'].isna()

In [36]:
print(dfT['LIVRAISON_MANQUANTE'].head(50))

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
Name: LIVRAISON_MANQUANTE, dtype: bool

In [37]:
#remplacer les valeurs manquantes par NON_RENSEIGNEE dans la colonne livraison :
dfT['LIVRAISON'] = dfT['LIVRAISON'].fillna('NON_RENSEIGNEE')

In [38]:
dfT.isnull().sum()

ARTCODE                   0
CDATE                     0
LIVRAISON                 0
VOYCLE                    0
PLALIB                    0
PLAMOTI                   0
SALNOM                    0
PLACHA1I                  0
TIECODE                   0
VOYDTD                    0
VOYHRD                    0
VOYDTF                    0
VOYHRF                    0
VOYPAL                    0
SITESALARIE               0
SITECAMION                0
PLAKM2                    0
Deposant                  0
OTSNUMBDX              3059
Type_TRANSPORT            0
CAPACITE                  0
SITE_CHAUFFEUR            0
Type_Tourne              0
Type de marchandise       0
Temprature               0
SITE                      0
LIVRAISON_MANQUANTE       0
dtype: int64

In [39]:
print(dfT.shape)

(494087, 27)

In [40]:
#pour la colonne OTSNUMBDX  1er on transformer le type en string et puis remplacer les valeurs manquantes par NON_RENSEIGNEE
dfT['OTSNUMBDX'] = dfT['OTSNUMBDX'].astype('string')
dfT['OTSNUMBDX'] = dfT['OTSNUMBDX'].fillna('NON_RENSEIGNE')

In [41]:
dfT.isnull().sum()

ARTCODE                0
CDATE                  0
LIVRAISON              0
VOYCLE                 0
PLALIB                 0
PLAMOTI                0
SALNOM                 0
PLACHA1I               0
TIECODE                0
VOYDTD                 0
VOYHRD                 0
VOYDTF                 0
VOYHRF                 0
VOYPAL                 0
SITESALARIE            0
SITECAMION             0
PLAKM2                 0
Deposant               0
OTSNUMBDX              0
Type_TRANSPORT         0
CAPACITE               0
SITE_CHAUFFEUR         0
Type_Tourne           0
Type de marchandise    0
Temprature            0
SITE                   0
LIVRAISON_MANQUANTE    0
dtype: int64

In [42]:
print(dfT.columns[dfT.columns.duplicated()])

Index([], dtype='object')

In [43]:
print(dfT['OTSNUMBDX'].isna().sum())

0

In [44]:
#verfication si tous les valeurs manquants sont  corriger
print("Nombre total de valeurs manquantes :", dfT.isna().sum().sum())

Nombre total de valeurs manquantes : 0

In [45]:
#verfication si il existe des valeurs vide 
print("Nombre de chaînes vides :", (dfT == '').sum().sum())

Nombre de chaînes vides : 0

In [46]:
#verfication s'il existe valeurs contenant uniquement des espaces
print("Nombre de valeurs contenant uniquement des espaces :",
      (dfT.select_dtypes(include='object') == ' ').sum().sum())

Nombre de valeurs contenant uniquement des espaces : 0

In [47]:
#calculer le nombre des valeurs dupliqué
doublons = dfT.duplicated().sum()
print("le nombre des valeur duplique ",doublons)
#voir les lignes qui contient les valeur duplique
df_doublons = dfT[dfT.duplicated(keep=False)]
print(df_doublons.head(20))

le nombre des valeur duplique  654
       ARTCODE                    CDATE LIVRAISON   VOYCLE           PLALIB  \
149265    T011  2026-01-07 00:00:00.000      1055  8108470  TRANSPORT FRUIT
149269    T011  2026-01-07 00:00:00.000      1078  8108458  TRANSPORT FRUIT
149343    T011  2026-01-07 00:00:00.000      1104  8108481  TRANSPORT FRUIT
149349    T011  2026-01-07 00:00:00.000      1155  8108502  TRANSPORT FRUIT
149350    T011  2026-01-07 00:00:00.000      1155  8108502  TRANSPORT FRUIT
149353    T011  2026-01-07 00:00:00.000      1184  8108502  TRANSPORT FRUIT
149356    T011  2026-01-07 00:00:00.000      1192  8108458  TRANSPORT FRUIT
149357    T011  2026-01-07 00:00:00.000      1192  8108458  TRANSPORT FRUIT
149362    T011  2026-01-07 00:00:00.000      1221  8108458  TRANSPORT FRUIT
149422    T011  2026-01-07 00:00:00.000      1392  8108502  TRANSPORT FRUIT
150177    T011  2026-01-13 00:00:00.000      1308  8128363  TRANSPORT FRUIT
150195    T011  2026-01-14 00:00:00.000      1055  8133718  TRANSPORT FRUIT
150201    T011  2026-01-14 00:00:00.000      1078  8133726  TRANSPORT FRUIT
150254    T011  2026-01-14 00:00:00.000      1110  8133745  TRANSPORT FRUIT
150259    T011  2026-01-14 00:00:00.000      1155  8133726  TRANSPORT FRUIT
150262    T011  2026-01-14 00:00:00.000      1165  8133738  TRANSPORT FRUIT
150263    T011  2026-01-14 00:00:00.000      1165  8133738  TRANSPORT FRUIT
150268    T011  2026-01-14 00:00:00.000      1189  8133718  TRANSPORT FRUIT
150271    T011  2026-01-14 00:00:00.000      1200  8133712  TRANSPORT FRUIT
150385    T011  2026-01-14 00:00:00.000      1262  8133712  TRANSPORT FRUIT

          PLAMOTI               SALNOM PLACHA1I TIECODE  \
149265  9134TU135        YASSINE HOMRI   412599     AZI
149269  9916TU215     RAYEN ABDELKADER   100537     AZI
149343  6673TU193         FAROUK TALBI   101397     AZI
149349  9134TU135          CHIHI HELMI   412361     AZI
149350  9134TU135          CHIHI HELMI   412361     AZI
149353  9134TU135          CHIHI HELMI   412361     AZI
149356  9916TU215     RAYEN ABDELKADER   100537     AZI
149357  9916TU215     RAYEN ABDELKADER   100537     AZI
149362  9916TU215     RAYEN ABDELKADER   100537     AZI
149422  9134TU135          CHIHI HELMI   412361     AZI
150177   713TU193         HAMDI MRABET   101327     AZI
150195  6064TU197         AMRI SKANDER     1071     AZI
150201  9916TU215     RAYEN ABDELKADER   100537     AZI
150254  8336TU215  MOHAMED ALI HAMMEMI   412660     AZI
150259  9916TU215     RAYEN ABDELKADER   100537     AZI
150262  5084TU198      AHMED BOUGHRARA   412659     AZI
150263  5084TU198      AHMED BOUGHRARA   412659     AZI
150268  6064TU197         AMRI SKANDER     1071     AZI
150271  4963TU204         HAMDI MRABET   101327     AZI
150385  4963TU204         HAMDI MRABET   101327     AZI

                         VOYDTD  ...  Deposant    OTSNUMBDX  Type_TRANSPORT  \
149265  2026-01-10 00:00:00.000  ...       THO  2,60105E+12              LT
149269  2026-01-10 00:00:00.000  ...       THO  2,60105E+12              LT
149343  2026-01-11 00:00:00.000  ...       THO  2,60105E+12              LT
149349  2026-01-11 00:00:00.000  ...       THO  2,60105E+12              LT
149350  2026-01-11 00:00:00.000  ...       THO  2,60105E+12              LT
149353  2026-01-11 00:00:00.000  ...       THO  2,60105E+12              LT
149356  2026-01-10 00:00:00.000  ...       THO  2,60105E+12              LT
149357  2026-01-10 00:00:00.000  ...       THO  2,60105E+12              LT
149362  2026-01-10 00:00:00.000  ...       THO  2,60105E+12              LT
149422  2026-01-11 00:00:00.000  ...       THO  2,60105E+12              LT
150177  2026-01-14 00:00:00.000  ...       THO  2,60105E+12              LT
150195  2026-01-17 00:00:00.000  ...       THO  2,60105E+12              LT
150201  2026-01-16 00:00:00.000  ...       THO  2,60105E+12              LT
150254  2026-01-16 00:00:00.000  ...       THO  2,60105E+12              LT
150259  2026-01-16 00:00:00.000  ...       THO  2,60105E+12              LT
150262  2026-01-16 00:00:00.000  ...       THO  2,60105E+12              LT
150263  2026-01-16 00:00:00.000  ...       THO  2,60105E+12              LT
150268  2026-01-17 00:00:00.000  ...       THO  2,60105E+12              LT
150271  2026-01-18 00:00:00.000  ...       THO  2,60105E+12              LT
150385  2026-01-18 00:00:00.000  ...       THO  2,60105E+12              LT

        CAPACITE SITE_CHAUFFEUR Type_Tourne  Type de marchandise  \
149265       7.0            NAS     Facture                FRUIT
149269      10.0            NAS     Facture                FRUIT
149343       6.0            NAS     Facture                FRUIT
149349       7.0            NAS     Facture                FRUIT
149350       7.0            NAS     Facture                FRUIT
149353       7.0            NAS     Facture                FRUIT
149356      10.0            NAS     Facture                FRUIT
149357      10.0            NAS     Facture                FRUIT
149362      10.0            NAS     Facture                FRUIT
149422       7.0            NAS     Facture                FRUIT
150177      10.0            NAS     Facture                FRUIT
150195      10.0            NAS     Facture                FRUIT
150201      10.0            NAS     Facture                FRUIT
150254      10.0            NAS     Facture                FRUIT
150259      10.0            NAS     Facture                FRUIT
150262      10.0            NAS     Facture                FRUIT
150263      10.0            NAS     Facture                FRUIT
150268      10.0            NAS     Facture                FRUIT
150271       3.0            NAS     Facture                FRUIT
150385       3.0            NAS     Facture                FRUIT

              Temprature SITE LIVRAISON_MANQUANTE
149265  Temprature FRAIS  NAS               False
149269  Temprature FRAIS  NAS               False
149343  Temprature FRAIS  NAS               False
149349  Temprature FRAIS  NAS               False
149350  Temprature FRAIS  NAS               False
149353  Temprature FRAIS  NAS               False
149356  Temprature FRAIS  NAS               False
149357  Temprature FRAIS  NAS               False
149362  Temprature FRAIS  NAS               False
149422  Temprature FRAIS  NAS               False
150177  Temprature FRAIS  NAS               False
150195  Temprature FRAIS  NAS               False
150201  Temprature FRAIS  NAS               False
150254  Temprature FRAIS  NAS               False
150259  Temprature FRAIS  NAS               False
150262  Temprature FRAIS  NAS               False
150263  Temprature FRAIS  NAS               False
150268  Temprature FRAIS  NAS               False
150271  Temprature FRAIS  NAS               False
150385  Temprature FRAIS  NAS               False

[20 rows x 27 columns]

In [48]:
print("VOYCLE uniques :", dfT['VOYCLE'].nunique())

VOYCLE uniques : 86957

In [49]:
stats_voyages = dfT.groupby('VOYCLE').size()

print(stats_voyages.describe())

count    86957.000000
mean         5.681969
std          7.207738
min          1.000000
25%          1.000000
50%          3.000000
75%          7.000000
max         74.000000
dtype: float64

In [50]:
top_voyages = (
    dfT.groupby('VOYCLE')
       .size()
       .sort_values(ascending=False)
       .head(10)
)

print(top_voyages)

VOYCLE
8694741    74
8518054    68
8235434    68
8144419    66
8888325    64
8759948    63
8147038    62
8565265    62
8817047    60
8738317    59
dtype: int64

In [51]:
voyage_max = top_voyages.index[0]

print("VOYCLE :", voyage_max)

print(
    dfT[dfT['VOYCLE'] == voyage_max].to_string()
)

VOYCLE : 8694741
       ARTCODE                    CDATE    LIVRAISON   VOYCLE                      PLALIB    PLAMOTI           SALNOM PLACHA1I TIECODE                   VOYDTD  VOYHRD                   VOYDTF  VOYHRF  VOYPAL SITESALARIE SITECAMION  PLAKM2 Deposant         OTSNUMBDX Type_TRANSPORT  CAPACITE SITE_CHAUFFEUR Type_Tourne Type de marchandise          Temprature SITE  LIVRAISON_MANQUANTE
1524      T003  2026-05-29 00:00:00.000   GNA096-AD1  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     DGC  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-CBR17463             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
1525      T003  2026-05-29 00:00:00.000   GNA241-AD1  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     CSG  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-PRO26753             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
1529      T003  2026-05-29 00:00:00.000   HNA134-AD1  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     DGC  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-CBR17897             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
1530      T003  2026-05-29 00:00:00.000   HNA134-AD1  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     CSG  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS  CD2605-PRO26778F             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
1626      T003  2026-05-29 00:00:00.000   PNA033-AD1  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     CSG  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-PRO26749             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
1627      T003  2026-05-29 00:00:00.000   PNA395-AD1  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     CGN  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-NBR06480             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
1628      T003  2026-05-29 00:00:00.000   PNA675-AD1  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     CSG  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-PRO26858             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
1671      T003  2026-05-29 00:00:00.000   SBA001-A18  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     DGC  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS  CD2605-CBR17866F             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
1676      T003  2026-05-29 00:00:00.000   SBA001-A34  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     IND  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-MEN22295             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
1684      T003  2026-05-29 00:00:00.000  SNA012-AD31  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     IND  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS  CD2605-MEN22082F             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
1785      T003  2026-05-29 00:00:00.000   STU006-A85  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     DGC  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS  CD2605-CBR17756F             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
1786      T003  2026-05-29 00:00:00.000   STU006-A85  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     DGC  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS  CD2605-CBR17757F             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
1787      T003  2026-05-29 00:00:00.000   STU006-A85  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     IND  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS  CD2605-MEN22210F             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
1793      T003  2026-05-29 00:00:00.000   STU024-AD6  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     IND  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-MEN22286             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
1794      T003  2026-05-29 00:00:00.000   STU024-AD8  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     IND  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-MEN22284             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
14524     T003  2026-05-29 00:00:00.000   GNA242-AD1  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     CSG  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-PRO26786             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
14525     T003  2026-05-29 00:00:00.000   GNA257-AD1  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     CSG  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS  CD2605-PRO26838F             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
14662     T003  2026-05-29 00:00:00.000   PNA395-AD1  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     IND  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-MEN21994             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
14811     T003  2026-05-29 00:00:00.000   SBA001-A18  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     CGN  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-NBR06522             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
14817     T003  2026-05-29 00:00:00.000  SNA012-AD31  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     DGC  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS  CD2605-CBR17950F             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
14852     T003  2026-05-29 00:00:00.000   STU006-A85  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     GDI  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-BRA12217             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
14853     T003  2026-05-29 00:00:00.000   STU006-A85  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     DGC  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS  CD2605-CBR17911F             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
14854     T003  2026-05-29 00:00:00.000   STU006-A90  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     GDI  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS  CD2605-BRA12224F             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
80278     T003  2026-05-29 00:00:00.000   GNA211-AD1  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     DGC  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS  CD2605-CBR17529F             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
80352     T003  2026-05-29 00:00:00.000   PNA395-AD1  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     CSG  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS  CD2605-PRO26645F             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
80481     T003  2026-05-29 00:00:00.000   SBA001-A18  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     GDI  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-BRA12189             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
80482     T003  2026-05-29 00:00:00.000   SBA001-A18  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     DGC  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-CBR17874             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
80493     T003  2026-05-29 00:00:00.000  SNA012-AD16  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     IND  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-MEN22231             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
80495     T003  2026-05-29 00:00:00.000  SNA012-AD34  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     DGC  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS  CD2605-CBR17956F             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
80496     T003  2026-05-29 00:00:00.000   SNA012-AD7  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     IND  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS  CD2605-MEN22092F             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
80558     T003  2026-05-29 00:00:00.000   STU006-A85  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     IND  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-MEN22160             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
93065     T003  2026-05-29 00:00:00.000   BNA101-AD1  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     IND  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-MEN22152             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
93105     T003  2026-05-29 00:00:00.000   GNA222-AD1  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     CSG  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS  CD2605-PRO26824F             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
93107     T003  2026-05-29 00:00:00.000   GNA241-AD1  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     CSG  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS  CD2605-PRO26754F             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
93108     T003  2026-05-29 00:00:00.000   GNA249-AD1  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     CGN  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-NBR06532             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
93120     T003  2026-05-29 00:00:00.000   HNA134-AD1  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     CGN  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-NBR06516             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
93131     T003  2026-05-29 00:00:00.000   PNA327-AD1  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     CSG  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS  CD2605-PRO26791F             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
93132     T003  2026-05-29 00:00:00.000   PNA466-AD1  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     CGN  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-NBR06512             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
93261     T003  2026-05-29 00:00:00.000  SNA012-AD33  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     DGC  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-CBR17952             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
93266     T003  2026-05-29 00:00:00.000   STU006-A24  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     IND  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS  CD2605-MEN22247F             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
93285     T003  2026-05-29 00:00:00.000   STU006-A90  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     DGC  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS  CD2605-CBR17942F             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
93293     T003  2026-05-29 00:00:00.000   STU024-AD8  8694741  TRANSPORT CONTRLé // 12¡C  8564TU232  BEL HASSEN MOEZ      411     IND  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-MEN22159             LT      10.0            BAR     Facture               FRAIS    Temprature FRAIS  BAR                False
131747    T004  2026-05-29 00:00:00.000   GNA208-AD1  8694741           TRANSPORT AMBIANT  8564TU232  BEL HASSEN MOEZ      411     DGC  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-CBR17231             LT      10.0            BAR     Facture             AMBIANT  Temprature AMBIANT  BAR                False
131748    T004  2026-05-29 00:00:00.000   GNA211-AD1  8694741           TRANSPORT AMBIANT  8564TU232  BEL HASSEN MOEZ      411     DGN  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-GBR05700             LT      10.0            BAR     Facture             AMBIANT  Temprature AMBIANT  BAR                False
131757    T004  2026-05-29 00:00:00.000   PNA327-AD1  8694741           TRANSPORT AMBIANT  8564TU232  BEL HASSEN MOEZ      411     CSG  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS  CD2605-PRO26791S             LT      10.0            BAR     Facture             AMBIANT  Temprature AMBIANT  BAR                False
131758    T004  2026-05-29 00:00:00.000   PNA395-AD1  8694741           TRANSPORT AMBIANT  8564TU232  BEL HASSEN MOEZ      411     CSG  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS  CD2605-PRO26645S             LT      10.0            BAR     Facture             AMBIANT  Temprature AMBIANT  BAR                False
131784    T004  2026-05-29 00:00:00.000   STU006-A85  8694741           TRANSPORT AMBIANT  8564TU232  BEL HASSEN MOEZ      411     GDI  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-BRA12151             LT      10.0            BAR     Facture             AMBIANT  Temprature AMBIANT  BAR                False
131785    T004  2026-05-29 00:00:00.000   STU006-A85  8694741           TRANSPORT AMBIANT  8564TU232  BEL HASSEN MOEZ      411     DGC  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS  CD2605-CBR17756S             LT      10.0            BAR     Facture             AMBIANT  Temprature AMBIANT  BAR                False
131786    T004  2026-05-29 00:00:00.000   STU006-A85  8694741           TRANSPORT AMBIANT  8564TU232  BEL HASSEN MOEZ      411     IND  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-MEN22013             LT      10.0            BAR     Facture             AMBIANT  Temprature AMBIANT  BAR                False
131787    T004  2026-05-29 00:00:00.000   STU006-A90  8694741           TRANSPORT AMBIANT  8564TU232  BEL HASSEN MOEZ      411     GDI  2026-05-30 00:00:00.000     600  2026-05-30 00:00:00.000    1200    8.79         BAR        BAR       0     GIAS   CD2605-BRA12223             LT      10.0            BAR     Facture             AMBIANT  Temprature AMBIANT  BAR                False

In [52]:
print(
    dfT[dfT['VOYCLE'] == 8694741][
        [
            'VOYCLE',
            'CDATE',
            'VOYPAL',
            'SALNOM',
            'PLACHA1I',
            'VOYDTD',
            'VOYHRD',
            'VOYDTF',
            'VOYHRF',
            'LIVRAISON',
            'OTSNUMBDX',
            'Type_TRANSPORT',
            'CAPACITE',
            'SITE'
        ]
    ].to_string(index=False)
)

 VOYCLE                   CDATE  VOYPAL          SALNOM PLACHA1I                  VOYDTD  VOYHRD                  VOYDTF  VOYHRF   LIVRAISON        OTSNUMBDX Type_TRANSPORT  CAPACITE SITE
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  GNA096-AD1  CD2605-CBR17463             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  GNA241-AD1  CD2605-PRO26753             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  HNA134-AD1  CD2605-CBR17897             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  HNA134-AD1 CD2605-PRO26778F             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  PNA033-AD1  CD2605-PRO26749             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  PNA395-AD1  CD2605-NBR06480             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  PNA675-AD1  CD2605-PRO26858             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  SBA001-A18 CD2605-CBR17866F             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  SBA001-A34  CD2605-MEN22295             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200 SNA012-AD31 CD2605-MEN22082F             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  STU006-A85 CD2605-CBR17756F             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  STU006-A85 CD2605-CBR17757F             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  STU006-A85 CD2605-MEN22210F             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  STU024-AD6  CD2605-MEN22286             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  STU024-AD8  CD2605-MEN22284             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  GNA242-AD1  CD2605-PRO26786             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  GNA257-AD1 CD2605-PRO26838F             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  PNA395-AD1  CD2605-MEN21994             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  SBA001-A18  CD2605-NBR06522             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200 SNA012-AD31 CD2605-CBR17950F             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  STU006-A85  CD2605-BRA12217             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  STU006-A85 CD2605-CBR17911F             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  STU006-A90 CD2605-BRA12224F             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  GNA211-AD1 CD2605-CBR17529F             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  PNA395-AD1 CD2605-PRO26645F             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  SBA001-A18  CD2605-BRA12189             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  SBA001-A18  CD2605-CBR17874             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200 SNA012-AD16  CD2605-MEN22231             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200 SNA012-AD34 CD2605-CBR17956F             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  SNA012-AD7 CD2605-MEN22092F             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  STU006-A85  CD2605-MEN22160             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  BNA101-AD1  CD2605-MEN22152             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  GNA222-AD1 CD2605-PRO26824F             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  GNA241-AD1 CD2605-PRO26754F             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  GNA249-AD1  CD2605-NBR06532             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  HNA134-AD1  CD2605-NBR06516             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  PNA327-AD1 CD2605-PRO26791F             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  PNA466-AD1  CD2605-NBR06512             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200 SNA012-AD33  CD2605-CBR17952             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  STU006-A24 CD2605-MEN22247F             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  STU006-A90 CD2605-CBR17942F             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  STU024-AD8  CD2605-MEN22159             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  GNA208-AD1  CD2605-CBR17231             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  GNA211-AD1  CD2605-GBR05700             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  PNA327-AD1 CD2605-PRO26791S             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  PNA395-AD1 CD2605-PRO26645S             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  STU006-A85  CD2605-BRA12151             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  STU006-A85 CD2605-CBR17756S             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  STU006-A85  CD2605-MEN22013             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  STU006-A90  CD2605-BRA12223             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  STU006-A90  CD2605-GBR05823             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  GNA211-AD1 CD2605-CBR17529S             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  GNA257-AD1 CD2605-PRO26838S             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  SNA012-AD7 CD2605-MEN22092S             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  GNA241-AD1 CD2605-PRO26754S             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  GNA249-AD1  CD2605-PRO26839             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  SBA001-A18 CD2605-CBR17866S             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200 SNA012-AD31 CD2605-CBR17950S             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  STU006-A85  CD2605-CBR17723             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  STU006-A85 CD2605-CBR17757S             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  STU006-A85 CD2605-CBR17911S             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  STU006-A90 CD2605-BRA12224S             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200 STU040-AD34  CD2605-BRA12183             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  GNA222-AD1 CD2605-PRO26824S             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  HNA134-AD1 CD2605-PRO26778S             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  SBA001-A75  CD2605-GBR05771             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200 SNA012-AD31  CD2605-GBR05827             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200 SNA012-AD31 CD2605-MEN22082S             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200 SNA012-AD33  CD2605-GBR05829             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200 SNA012-AD34 CD2605-CBR17956S             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  STU006-A24  CD2605-MEN22000             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  STU006-A24 CD2605-MEN22247S             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  STU006-A85 CD2605-MEN22210S             LT      10.0  BAR
8694741 2026-05-29 00:00:00.000    8.79 BEL HASSEN MOEZ      411 2026-05-30 00:00:00.000     600 2026-05-30 00:00:00.000    1200  STU006-A90 CD2605-CBR17942S             LT      10.0  BAR

In [53]:
doublons_livraison = dfT.duplicated(
    subset=['VOYCLE', 'LIVRAISON', 'OTSNUMBDX'],
    keep=False
)

print("Doublons VOYCLE + LIVRAISON + OTSNUMBDX :",
      doublons_livraison.sum())

Doublons VOYCLE + LIVRAISON + OTSNUMBDX : 1223

In [54]:
print(
    dfT[doublons_livraison][
        ['VOYCLE', 'LIVRAISON', 'OTSNUMBDX', 'SALNOM', 'PLACHA1I']
    ]
    .sort_values(['VOYCLE', 'LIVRAISON'])
    .head(30)
    .to_string(index=False)
)

 VOYCLE LIVRAISON   OTSNUMBDX           SALNOM PLACHA1I
8108458      1078 2,60105E+12 RAYEN ABDELKADER   100537
8108458      1078 2,60105E+12 RAYEN ABDELKADER   100537
8108458      1192 2,60105E+12 RAYEN ABDELKADER   100537
8108458      1192 2,60105E+12 RAYEN ABDELKADER   100537
8108458      1221 2,60105E+12 RAYEN ABDELKADER   100537
8108458      1221 2,60105E+12 RAYEN ABDELKADER   100537
8108470      1055 2,60105E+12    YASSINE HOMRI   412599
8108470      1055 2,60105E+12    YASSINE HOMRI   412599
8108470      1189 2,60105E+12    YASSINE HOMRI   412599
8108470      1189 2,60105E+12    YASSINE HOMRI   412599
8108481      1104 2,60105E+12     FAROUK TALBI   101397
8108481      1104 2,60105E+12     FAROUK TALBI   101397
8108481      1235 2,60105E+12     FAROUK TALBI   101397
8108481      1235 2,60105E+12     FAROUK TALBI   101397
8108481      1274 2,60105E+12     FAROUK TALBI   101397
8108481      1274 2,60105E+12     FAROUK TALBI   101397
8108481      1320 2,60105E+12     FAROUK TALBI   101397
8108481      1320 2,60105E+12     FAROUK TALBI   101397
8108502      1155 2,60105E+12      CHIHI HELMI   412361
8108502      1155 2,60105E+12      CHIHI HELMI   412361
8108502      1184 2,60105E+12      CHIHI HELMI   412361
8108502      1184 2,60105E+12      CHIHI HELMI   412361
8108502      1355 2,60105E+12      CHIHI HELMI   412361
8108502      1355 2,60105E+12      CHIHI HELMI   412361
8108502      1392 2,60105E+12      CHIHI HELMI   412361
8108502      1392 2,60105E+12      CHIHI HELMI   412361
8128363      1308 2,60105E+12     HAMDI MRABET   101327
8128363      1308 2,60105E+12     HAMDI MRABET   101327
8133712      1035 2,60105E+12     HAMDI MRABET   101327
8133712      1035 2,60105E+12     HAMDI MRABET   101327

In [55]:
test = dfT[
    (dfT['VOYCLE'] == 8108502) &
    (dfT['LIVRAISON'] == '1155')
]

print(test.T)

                                      149349                   149350
ARTCODE                                 T011                     T011
CDATE                2026-01-07 00:00:00.000  2026-01-07 00:00:00.000
LIVRAISON                               1155                     1155
VOYCLE                               8108502                  8108502
PLALIB                       TRANSPORT FRUIT          TRANSPORT FRUIT
PLAMOTI                            9134TU135                9134TU135
SALNOM                           CHIHI HELMI              CHIHI HELMI
PLACHA1I                              412361                   412361
TIECODE                                  AZI                      AZI
VOYDTD               2026-01-11 00:00:00.000  2026-01-11 00:00:00.000
VOYHRD                                  1100                     1100
VOYDTF               2026-01-11 00:00:00.000  2026-01-11 00:00:00.000
VOYHRF                                  1630                     1630
VOYPAL                                 221.0                    221.0
SITESALARIE                             9901                     9901
SITECAMION                               BKS                      BKS
PLAKM2                                     0                        0
Deposant                                 THO                      THO
OTSNUMBDX                        2,60105E+12              2,60105E+12
Type_TRANSPORT                            LT                       LT
CAPACITE                                 7.0                      7.0
SITE_CHAUFFEUR                           NAS                      NAS
Type_Tourne                        Facture                 Facture
Type de marchandise                    FRUIT                    FRUIT
Temprature                Temprature FRAIS        Temprature FRAIS
SITE                                     NAS                      NAS
LIVRAISON_MANQUANTE                    False                    False

In [56]:
dfT = dfT.drop_duplicates()

In [57]:
# Suppression uniquement des doublons strictement identiques
print("Nombre de doublons restants :", dfT.duplicated().sum())

Nombre de doublons restants : 0

In [58]:
#c'est un petite resume dediee a la dataset TMS.csv
rapport = pd.DataFrame({
    'colonne': dfT.columns,
    'type': dfT.dtypes.astype(str).values,
    'nb_valeurs_manquantes': dfT.isna().sum().values,
    'nb_valeurs_uniques': dfT.nunique().values
})

print(rapport)

                colonne     type  nb_valeurs_manquantes  nb_valeurs_uniques
0               ARTCODE   object                      0                  31
1                 CDATE   object                      0                 235
2             LIVRAISON   object                      0                4158
3                VOYCLE    int64                      0               86957
4                PLALIB   object                      0                  31
5               PLAMOTI   object                      0                 311
6                SALNOM   object                      0                 396
7              PLACHA1I   object                      0                 422
8               TIECODE   object                      0                  99
9                VOYDTD   object                      0                 219
10               VOYHRD    int64                      0                 861
11               VOYDTF   object                      0                 239
12               VOYHRF    int64                      0                 902
13               VOYPAL  float64                      0                3958
14          SITESALARIE   object                      0                  14
15           SITECAMION   object                      0                  13
16               PLAKM2    int64                      0                 349
17             Deposant   object                      0                   5
18            OTSNUMBDX   string                      0              422285
19       Type_TRANSPORT   object                      0                   3
20             CAPACITE  float64                      0                  21
21       SITE_CHAUFFEUR   object                      0                  13
22         Type_Tourne   object                      0                   3
23  Type de marchandise   object                      0                   5
24          Temprature   object                      0                   3
25                 SITE   object                      0                  12
26  LIVRAISON_MANQUANTE     bool                      0                   2

<h1 style="color:red; text-align:center">le nettoyage de fichier Mobility.csv</h1>
<h1 style="color:red; text-align:center">le nettoyage de fichier chauffeurs sans mobility</h1>

In [59]:
#dfM = pd.read_csv('mobility.csv', sep=';')
dfM = pd.read_csv('mobility.csv', sep=';', encoding='latin-1')

C:\Users\nourg\AppData\Local\Temp\ipykernel_7748\3061588408.py:2: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  dfM = pd.read_csv('mobility.csv', sep=';', encoding='latin-1')

In [60]:
print(dfM.head())

    voycle chauff camion                 date_idb     name_event  \
0  8120158    120    NaN  2026-01-11 20:56:08.000     fin_voyage
1  8120158    120    NaN  2026-01-11 20:56:09.000  depart_voyage
2  8119945    120    NaN  2026-01-11 20:56:09.000     fin_voyage
3  8119945    120    NaN  2026-01-11 20:56:09.000  depart_voyage
4  8119466    120    NaN  2026-01-11 20:56:10.000     fin_voyage

                date_saisi      KM commentaire client  next_destination  \
0  2026-01-10 12:15:00.000  590305         NaN    NaN               NaN
1  2026-01-10 11:30:00.000  590299         NaN    NaN               NaN
2  2026-01-10 11:00:00.000  590299         NaN    NaN               NaN
3  2026-01-10 10:15:00.000  590294         NaN    NaN               NaN
4  2026-01-10 10:00:00.000  590294         NaN    NaN               NaN

   images  time_event event_from  tempurature  SITE  voyage_str  nature_voyage
0     NaN         NaN    android          NaN   NaN         NaN            NaN
1     NaN         NaN    android          NaN   NaN         NaN            NaN
2     NaN         NaN    android          NaN   NaN         NaN            NaN
3     NaN         NaN    android          NaN   NaN         NaN            NaN
4     NaN         NaN    android          NaN   NaN         NaN            NaN

In [61]:
print(dfM.shape)

(482470, 17)

In [62]:
dfM.isnull().sum()

voycle                   0
chauff                   0
camion               13299
date_idb                 0
name_event               0
date_saisi               0
KM                       0
commentaire         481933
client              118016
next_destination    482470
images              482470
time_event           13299
event_from               0
tempurature         482470
SITE                482470
voyage_str          482470
nature_voyage       482470
dtype: int64

In [63]:
dfM.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 482470 entries, 0 to 482469
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   voycle            482470 non-null  object
 1   chauff            482470 non-null  object
 2   camion            469171 non-null  object
 3   date_idb          482470 non-null  object
 4   name_event        482470 non-null  object
 5   date_saisi        482470 non-null  object
 6   KM                482470 non-null  object
 7   commentaire       537 non-null     object
 8   client            364454 non-null  object
 9   next_destination  0 non-null       float64
 10  images            0 non-null       float64
 11  time_event        469171 non-null  float64
 12  event_from        482470 non-null  object
 13  tempurature       0 non-null       float64
 14  SITE              0 non-null       float64
 15  voyage_str        0 non-null       float64
 16  nature_voyage     0 non-null       float64
dtypes: float64(7), object(10)
memory usage: 62.6+ MB

In [64]:
dfM.dtypes

voycle               object
chauff               object
camion               object
date_idb             object
name_event           object
date_saisi           object
KM                   object
commentaire          object
client               object
next_destination    float64
images              float64
time_event          float64
event_from           object
tempurature         float64
SITE                float64
voyage_str          float64
nature_voyage       float64
dtype: object

In [65]:
colonnes_vides = dfM.columns[dfM.isna().all()]

print("Colonnes complètement vides :")
print(colonnes_vides.tolist())

Colonnes complètement vides :
['next_destination', 'images', 'tempurature', 'SITE', 'voyage_str', 'nature_voyage']

In [66]:
# Remplacement des valeurs manquantes par des valeurs explicites

dfM['next_destination'] = dfM['next_destination'].fillna('Non précisée')
dfM['images'] = dfM['images'].fillna('Non disponible')
dfM['tempurature'] = dfM['tempurature'].fillna('Inconnue')
dfM['SITE'] = dfM['SITE'].fillna('Non précisé')
dfM['voyage_str'] = dfM['voyage_str'].fillna('Non précisé')
dfM['nature_voyage'] = dfM['nature_voyage'].fillna('Non précisée')

In [67]:
dfM.isnull().sum()

voycle                   0
chauff                   0
camion               13299
date_idb                 0
name_event               0
date_saisi               0
KM                       0
commentaire         481933
client              118016
next_destination         0
images                   0
time_event           13299
event_from               0
tempurature              0
SITE                     0
voyage_str               0
nature_voyage            0
dtype: int64

In [68]:
dfM['commentaire'] = dfM['commentaire'].fillna('Aucun commentaire')

In [69]:
dfM['date_idb'] = pd.to_datetime(dfM['date_idb'])
dfM['date_saisi'] = pd.to_datetime(dfM['date_saisi'])

dfM['delai_saisie_min'] = (
    dfM['date_idb'] - dfM['date_saisi']
).dt.total_seconds() / 60

In [70]:
print(dfM['delai_saisie_min'].describe())

count    482470.000000
mean         54.321699
std         247.952573
min       -2492.166667
25%           0.466667
50%           0.833333
75%           2.133333
max        5322.750000
Name: delai_saisie_min, dtype: float64

In [71]:
#cette fonction permter de faire une segmentation de delai de saisir de date par le chauffeur
def categorie_remontee(x):
    if pd.isna(x):
        return 'Non calculable'
    elif x < 0:
        return 'Anomalie'
    elif x < 5:
        return '< 5 min'
    elif x < 10:
        return '5 à 10 min'
    elif x < 60:
        return '10 à 60 min'
    else:
        return '> 60 min'

dfM['categorie_remontee'] = dfM['delai_saisie_min'].apply(categorie_remontee)

In [72]:
dfM.isnull().sum()

voycle                     0
chauff                     0
camion                 13299
date_idb                   0
name_event                 0
date_saisi                 0
KM                         0
commentaire                0
client                118016
next_destination           0
images                     0
time_event             13299
event_from                 0
tempurature                0
SITE                       0
voyage_str                 0
nature_voyage              0
delai_saisie_min           0
categorie_remontee         0
dtype: int64

In [73]:
print(dfM['camion'].isnull().sum())

13299

In [74]:
print(dfM[['date_idb', 'date_saisi', 'time_event', 'name_event']].head(20))

              date_idb          date_saisi    time_event     name_event
0  2026-01-11 20:56:08 2026-01-10 12:15:00           NaN     fin_voyage
1  2026-01-11 20:56:09 2026-01-10 11:30:00           NaN  depart_voyage
2  2026-01-11 20:56:09 2026-01-10 11:00:00           NaN     fin_voyage
3  2026-01-11 20:56:09 2026-01-10 10:15:00           NaN  depart_voyage
4  2026-01-11 20:56:10 2026-01-10 10:00:00           NaN     fin_voyage
5  2026-01-11 20:56:10 2026-01-10 08:30:00           NaN  depart_voyage
6  2026-01-30 09:57:33 2026-01-30 09:57:00  1.769763e+09     dep_client
7  2026-01-30 09:57:46 2026-01-30 09:57:00  1.769763e+09     arv_client
8  2026-01-30 09:57:57 2026-01-30 09:55:00  1.769763e+09     dep_client
9  2026-01-30 09:58:06 2026-01-30 09:58:00  1.769763e+09     arv_client
10 2026-01-30 09:58:20 2026-01-30 09:58:00  1.769764e+09     arv_client
11 2026-01-30 09:58:51 2026-01-30 09:58:00  1.769764e+09     dep_client
12 2026-01-30 09:58:55 2026-01-30 09:58:00  1.769764e+09     arv_client
13 2026-01-30 09:58:57 2026-01-30 09:58:00  1.769764e+09     arv_client
14 2026-01-30 09:59:45 2026-01-30 09:59:00  1.769764e+09     dep_client
15 2026-01-30 09:59:51 2026-01-30 09:59:00  1.769764e+09     dep_client
16 2026-01-30 10:00:05 2026-01-30 09:59:00  1.769764e+09     arv_client
17 2026-01-30 10:00:18 2026-01-30 10:00:00  1.769764e+09  depart_voyage
18 2026-01-30 10:00:19 2026-01-30 10:00:00  1.769764e+09     arv_client
19 2026-01-30 10:00:22 2026-01-30 10:00:00  1.769764e+09     arv_client

In [75]:
dfM['time_event']= pd.to_datetime(dfM['time_event'],
  unit='s',
    errors='coerce')

In [76]:
print(dfM[['time_event','name_event']].head(20))

            time_event     name_event
0                  NaT     fin_voyage
1                  NaT  depart_voyage
2                  NaT     fin_voyage
3                  NaT  depart_voyage
4                  NaT     fin_voyage
5                  NaT  depart_voyage
6  2026-01-30 08:57:32     dep_client
7  2026-01-30 08:57:46     arv_client
8  2026-01-30 08:57:55     dep_client
9  2026-01-30 08:58:07     arv_client
10 2026-01-30 08:58:20     arv_client
11 2026-01-30 08:58:51     dep_client
12 2026-01-30 08:58:55     arv_client
13 2026-01-30 08:58:54     arv_client
14 2026-01-30 08:59:47     dep_client
15 2026-01-30 08:59:51     dep_client
16 2026-01-30 09:00:05     arv_client
17 2026-01-30 09:00:16  depart_voyage
18 2026-01-30 09:00:18     arv_client
19 2026-01-30 09:00:22     arv_client

In [77]:
print(dfM['time_event'].isnull().sum())

13299

In [78]:
dfM['time_event'].isna().sum()

np.int64(13299)

In [79]:
#cette instruction sera  montre la pourcentage de la valeurs maquants en relation de le nome de time event 
dfM[dfM['time_event'].isna()]['name_event'].value_counts(normalize=True).mul(100).round(2)

name_event
arv_client       38.78
dep_client       37.55
depart_voyage    13.90
fin_voyage        9.77
Name: proportion, dtype: float64

In [80]:
print(dfM['time_event'].dtype)

datetime64[ns]

In [81]:
dfM['delai_sai_even'] = (dfM['date_saisi']-dfM['time_event']).dt.total_seconds() / 60

In [82]:
print(dfM['delai_sai_even'].head(20))

0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
5           NaN
6     59.466667
7     59.233333
8     57.083333
9     59.883333
10    59.666667
11    59.150000
12    59.083333
13    59.100000
14    59.216667
15    59.150000
16    58.916667
17    59.733333
18    59.700000
19    59.633333
Name: delai_sai_even, dtype: float64

In [83]:
print(dfM[
    ['date_idb', 'date_saisi', 'time_event', 'name_event', 'delai_sai_even']
].iloc[6:20])

              date_idb          date_saisi          time_event     name_event  \
6  2026-01-30 09:57:33 2026-01-30 09:57:00 2026-01-30 08:57:32     dep_client
7  2026-01-30 09:57:46 2026-01-30 09:57:00 2026-01-30 08:57:46     arv_client
8  2026-01-30 09:57:57 2026-01-30 09:55:00 2026-01-30 08:57:55     dep_client
9  2026-01-30 09:58:06 2026-01-30 09:58:00 2026-01-30 08:58:07     arv_client
10 2026-01-30 09:58:20 2026-01-30 09:58:00 2026-01-30 08:58:20     arv_client
11 2026-01-30 09:58:51 2026-01-30 09:58:00 2026-01-30 08:58:51     dep_client
12 2026-01-30 09:58:55 2026-01-30 09:58:00 2026-01-30 08:58:55     arv_client
13 2026-01-30 09:58:57 2026-01-30 09:58:00 2026-01-30 08:58:54     arv_client
14 2026-01-30 09:59:45 2026-01-30 09:59:00 2026-01-30 08:59:47     dep_client
15 2026-01-30 09:59:51 2026-01-30 09:59:00 2026-01-30 08:59:51     dep_client
16 2026-01-30 10:00:05 2026-01-30 09:59:00 2026-01-30 09:00:05     arv_client
17 2026-01-30 10:00:18 2026-01-30 10:00:00 2026-01-30 09:00:16  depart_voyage
18 2026-01-30 10:00:19 2026-01-30 10:00:00 2026-01-30 09:00:18     arv_client
19 2026-01-30 10:00:22 2026-01-30 10:00:00 2026-01-30 09:00:22     arv_client

    delai_sai_even
6        59.466667
7        59.233333
8        57.083333
9        59.883333
10       59.666667
11       59.150000
12       59.083333
13       59.100000
14       59.216667
15       59.150000
16       58.916667
17       59.733333
18       59.700000
19       59.633333

In [84]:
dfM.isnull().sum()

voycle                     0
chauff                     0
camion                 13299
date_idb                   0
name_event                 0
date_saisi                 0
KM                         0
commentaire                0
client                118016
next_destination           0
images                     0
time_event             13299
event_from                 0
tempurature                0
SITE                       0
voyage_str                 0
nature_voyage              0
delai_saisie_min           0
categorie_remontee         0
delai_sai_even         13299
dtype: int64

In [85]:
#pour les valeurs de time event manquante je creer un indicateur(colonne) qui contient les valeur nan
dfM['time_event_manquante']=dfM['time_event'].isna()

In [86]:
print(dfM['time_event_manquante'].value_counts())

time_event_manquante
False    469171
True      13299
Name: count, dtype: int64

In [87]:
dfM.isnull().sum()

voycle                       0
chauff                       0
camion                   13299
date_idb                     0
name_event                   0
date_saisi                   0
KM                           0
commentaire                  0
client                  118016
next_destination             0
images                       0
time_event               13299
event_from                   0
tempurature                  0
SITE                         0
voyage_str                   0
nature_voyage                0
delai_saisie_min             0
categorie_remontee           0
delai_sai_even           13299
time_event_manquante         0
dtype: int64

In [88]:
print(dfT.columns.tolist())

['ARTCODE', 'CDATE', 'LIVRAISON', 'VOYCLE', 'PLALIB', 'PLAMOTI', 'SALNOM', 'PLACHA1I', 'TIECODE', 'VOYDTD', 'VOYHRD', 'VOYDTF', 'VOYHRF', 'VOYPAL', 'SITESALARIE', 'SITECAMION', 'PLAKM2', 'Deposant', 'OTSNUMBDX', 'Type_TRANSPORT', 'CAPACITE', 'SITE_CHAUFFEUR', 'Type_Tourn\x8ee', 'Type de marchandise', 'Temp\x8erature', 'SITE', 'LIVRAISON_MANQUANTE']

In [89]:
print(dfT[['VOYCLE', 'PLAMOTI']].head())

    VOYCLE    PLAMOTI
0  8289736  9471TU205
1  8289956   527TU174
2  8289956   527TU174
3  8235406  8564TU232
4  8235406  8564TU232

In [90]:
print(dfT['VOYCLE'].dtype)
print(dfM['voycle'].dtype)

int64
object

In [91]:
dfT['VOYCLE']=dfT['VOYCLE'].astype('str')
dfM['voycle']=dfM['voycle'].astype('str')

In [92]:
dfT.head()

,ARTCODE,CDATE,LIVRAISON,VOYCLE,PLALIB,PLAMOTI,SALNOM,PLACHA1I,TIECODE,VOYDTD,...,Deposant,OTSNUMBDX,Type_TRANSPORT,CAPACITE,SITE_CHAUFFEUR,Type_Tourne,Type de marchandise,Temprature,SITE,LIVRAISON_MANQUANTE
0,T004,2026-02-20 00:00:00.000,9004,8289736,TRANSPORT AMBIANT,9471TU205,BEN BRAHIM ABDELKADER,418,CRISTAL,2026-02-23 00:00:00.000,...,EXTERNE,DIV0013362,LT,0.0,BAR,Facture,AMBIANT,Temprature AMBIANT,BAR,False
1,T004,2026-02-20 00:00:00.000,BKS042-AD1,8289956,TRANSPORT AMBIANT,527TU174,TALEB SAMI,428,CSG,2026-02-21 00:00:00.000,...,GIAS,CD2602-PGF08443,LT,3.0,GAF,Facture,AMBIANT,Temprature AMBIANT,GAF,False
2,T004,2026-02-20 00:00:00.000,BKS051-AD1,8289956,TRANSPORT AMBIANT,527TU174,TALEB SAMI,428,CSG,2026-02-21 00:00:00.000,...,GIAS,CD2602-PGF08383,LT,3.0,GAF,Facture,AMBIANT,Temprature AMBIANT,GAF,False
3,T004,2026-02-09 00:00:00.000,STU006-A90,8235406,TRANSPORT AMBIANT,8564TU232,BEL HASSEN MOEZ,411,DGC,2026-02-10 00:00:00.000,...,GIAS,CD2602-CBR04738,LT,10.0,BAR,Facture,AMBIANT,Temprature AMBIANT,BAR,False
4,T004,2026-02-09 00:00:00.000,STU006-A90,8235406,TRANSPORT AMBIANT,8564TU232,BEL HASSEN MOEZ,411,DGC,2026-02-10 00:00:00.000,...,GIAS,CD2602-CBR04807,LT,10.0,BAR,Facture,AMBIANT,Temprature AMBIANT,BAR,False

In [93]:
print(dfT['VOYCLE'].dtype)
print(dfM['voycle'].dtype)

object
object

In [94]:
print("doublons Voycle :",dfT['VOYCLE'].duplicated().sum())

doublons Voycle : 406476

In [95]:
voyages_sans_camion =dfM.loc[dfM['camion'].isna(),'voycle'].unique()
print("voyages mobility sans camion :",len(voyages_sans_camion))

correspondanse_tms=dfT[dfT['VOYCLE'].isin(voyages_sans_camion)]
print("voyages retrouve dans tms qui sont correspondanse a la mobility :",
      correspondanse_tms['VOYCLE'].nunique())

voyages mobility sans camion : 773
voyages retrouve dans tms qui sont correspondanse a la mobility : 755

In [96]:
tms_camion=dfT[dfT['VOYCLE'].isin(voyages_sans_camion)]
[['VOYCLE','PLAMOTI']].copy()

[['VOYCLE', 'PLAMOTI']]

In [97]:
nb_camion_par_voyage=(tms_camion.groupby('VOYCLE')['PLAMOTI'].nunique())
print(nb_camion_par_voyage.value_counts().sort_index())

PLAMOTI
1    755
Name: count, dtype: int64

In [98]:
mapping_tms = (
    tms_camion
    .dropna(subset=['PLAMOTI'])
    .drop_duplicates(subset=['VOYCLE'])
    [['VOYCLE', 'PLAMOTI']]
)

In [99]:
print(mapping_tms.shape)
print(mapping_tms.head())

(755, 2)
      VOYCLE    PLAMOTI
128  8290517  2471TU192
131  8290175  4956TU204
149  8237327  4593TU169
184  8288296  2820TU173
194  8290397  8564TU232

In [100]:
#creation de la dictionnaire voycle->PLAMOTI
mapping_dict=mapping_tms.set_index('VOYCLE')['PLAMOTI']
#faire le rechercher de camion tms pour chaque voyage de mobility
dfM['camion_tms']=dfM['voycle'].map(mapping_dict)

In [101]:
#remplacer les valeurs manquantes
dfM['camion']=dfM['camion'].fillna(dfM['camion_tms'])

In [102]:
#afficher les nombre des valeurs manquante qui sont restent
print("camion manquant apres :",dfM['camion'].isna().sum())

camion manquant apres : 503

In [103]:
print("les nbrs des camions recupere depuis tms:",dfM['camion_tms'].notna().sum())

les nbrs des camions recupere depuis tms: 18968

In [104]:
#verification les voyages qui sont restent sans camions
voyages_restant=dfM.loc[dfM['camion'].isna(),'voycle'].unique()
print("nombre de voyages restant sans camion: ",len(voyages_restant))

nombre de voyages restant sans camion:  18

In [105]:
print(voyages_restant[:18])

['8,11E+13' '8133067' '8,14E+13' '8189389' '8,27E+13' '8255599' '8,26E+13'
 '8269572' '8261635' '8332029' '8324775' '8349584' '8353464' '8,29E+13'
 '8500638' '8425502' '8,42E+13' '8,44E+13']

In [106]:
voyage_tms = set(dfT['VOYCLE'])
voyages_non_trouves=[
    v for v in voyages_restant
    if v not in voyage_tms
]
print(
    "voyages mobility non retrouves dans tms :",len(voyages_non_trouves))

voyages mobility non retrouves dans tms : 18

In [107]:
dfM.isnull().sum()

voycle                       0
chauff                       0
camion                     503
date_idb                     0
name_event                   0
date_saisi                   0
KM                           0
commentaire                  0
client                  118016
next_destination             0
images                       0
time_event               13299
event_from                   0
tempurature                  0
SITE                         0
voyage_str                   0
nature_voyage                0
delai_saisie_min             0
categorie_remontee           0
delai_sai_even           13299
time_event_manquante         0
camion_tms              463502
dtype: int64

In [108]:
print(dfM.loc[
    dfM['voycle'].isin(voyages_restant),'voycle'].tolist())

['8,11E+13', '8,11E+13', '8,11E+13', '8,11E+13', '8,11E+13', '8,11E+13', '8,11E+13', '8,11E+13', '8,11E+13', '8,11E+13', '8,14E+13', '8,14E+13', '8,14E+13', '8,14E+13', '8,14E+13', '8,14E+13', '8,14E+13', '8,14E+13', '8,14E+13', '8,14E+13', '8,14E+13', '8,14E+13', '8,14E+13', '8,14E+13', '8,14E+13', '8,14E+13', '8,14E+13', '8133067', '8133067', '8133067', '8133067', '8133067', '8133067', '8,14E+13', '8,14E+13', '8,14E+13', '8,14E+13', '8,14E+13', '8,14E+13', '8,14E+13', '8189389', '8189389', '8189389', '8189389', '8189389', '8189389', '8189389', '8189389', '8189389', '8189389', '8189389', '8189389', '8,26E+13', '8,26E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8255599', '8255599', '8255599', '8255599', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,27E+13', '8,27E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,27E+13', '8189389', '8189389', '8189389', '8189389', '8189389', '8189389', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,29E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8269572', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8269572', '8269572', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8269572', '8269572', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8255599', '8255599', '8255599', '8255599', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8255599', '8255599', '8255599', '8255599', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,26E+13', '8,26E+13', '8261635', '8261635', '8261635', '8261635', '8261635', '8261635', '8261635', '8261635', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8269572', '8269572', '8269572', '8269572', '8269572', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8332029', '8332029', '8332029', '8332029', '8332029', '8332029', '8332029', '8332029', '8332029', '8332029', '8332029', '8332029', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,26E+13', '8,26E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,26E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8269572', '8269572', '8269572', '8269572', '8269572', '8,27E+13', '8,27E+13', '8,27E+13', '8,26E+13', '8,27E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,27E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,27E+13', '8,27E+13', '8,26E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,26E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,26E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,27E+13', '8,27E+13', '8269572', '8269572', '8269572', '8269572', '8269572', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8255599', '8255599', '8255599', '8255599', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,27E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,27E+13', '8,27E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,26E+13', '8,27E+13', '8,27E+13', '8324775', '8324775', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8324775', '8324775', '8324775', '8324775', '8324775', '8324775', '8349584', '8349584', '8353464', '8353464', '8349584', '8349584', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8,29E+13', '8353464', '8353464', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8500638', '8,42E+13', '8,42E+13', '8,42E+13', '8,42E+13', '8,42E+13', '8,42E+13', '8,42E+13', '8,42E+13', '8,42E+13', '8,42E+13', '8,42E+13', '8,42E+13', '8,42E+13', '8,42E+13', '8,42E+13', '8,42E+13', '8,42E+13', '8,42E+13', '8,42E+13', '8,42E+13', '8425502', '8425502', '8425502', '8425502', '8,42E+13', '8,42E+13', '8,42E+13', '8,42E+13', '8,42E+13', '8,42E+13', '8,42E+13', '8,42E+13', '8,44E+13', '8,44E+13', '8,44E+13', '8,44E+13', '8,44E+13', '8,44E+13', '8,44E+13', '8,44E+13', '8,44E+13', '8,44E+13', '8,44E+13', '8,44E+13']

In [109]:
print(dfM.loc[
    dfM['voycle'].isin(voyages_restant),
    ['voycle', 'camion']
].drop_duplicates())

          voycle     camion
1567    8,11E+13  8723TU196
16958   8,11E+13        NaN
19722   8,11E+13  9288TU232
24916   8,14E+13  9471TU205
30635   8,14E+13  2589TU257
37706   8,14E+13  8050TU209
37813    8133067  9657TU177
40066    8133067        NaN
43036   8,14E+13        NaN
46618    8189389        NaN
57258   8,26E+13  3827TU166
71576   8,27E+13   RS189327
71577   8,27E+13        NaN
71959    8255599  2150TU174
71964    8255599        NaN
73895   8,26E+13  2771TU229
73897   8,26E+13        NaN
74002   8,27E+13  2695TU198
74005   8,27E+13  6684TU223
77987    8189389  1181TU202
80808   8,27E+13  2773TU229
81050   8,27E+13  9109TU209
83170   8,27E+13  1185TU202
88223   8,29E+13  6942TU217
89974    8269572   622TU240
89997    8269572        NaN
96185   8,26E+13  6155TU201
111981  8,26E+13  2573TU195
112475   8261635  1158TU195
112476   8261635        NaN
115396   8332029  2374TU173
115398   8332029        NaN
117715  8,26E+13  2820TU173
117956  8,26E+13  6071TU197
121196  8,26E+13   622TU240
126003  8,27E+13  2203TU185
126019  8,27E+13  2712TU210
138216   8324775  9288TU232
138218   8324775        NaN
140029  8,29E+13  7702TU202
144111   8349584  9858TU243
144114   8349584        NaN
146596   8353464  1087TU211
146603   8353464        NaN
149939  8,29E+13  2820TU173
153402  8,29E+13        NaN
191651   8500638  7819TU222
191660   8500638        NaN
201946  8,42E+13  3446TU174
204579   8425502  9473TU205
204583   8425502        NaN
205398  8,42E+13  1651TU212
205615  8,42E+13  8226TU215
205617  8,42E+13        NaN
208816  8,44E+13  1087TU211
214282  8,44E+13  1773TU188
216088  8,44E+13  8585TU202
216089  8,44E+13        NaN

In [110]:
dfT.groupby('VOYCLE')['PLAMOTI'].nunique().sort_values(ascending=False).head(20)

VOYCLE
8604279    2
8638253    2
7074462    1
8679679    1
8679851    1
8679850    1
8679845    1
8679844    1
8679718    1
8679693    1
8679684    1
8679680    1
8679677    1
8679853    1
8679658    1
8679657    1
8679653    1
8679648    1
8679647    1
8679646    1
Name: PLAMOTI, dtype: int64

In [111]:
multi_camion_tms = (
    dfT.groupby('VOYCLE')['PLAMOTI']
    .nunique()
    .reset_index(name='nb_camions')
)

print(
    multi_camion_tms[
        multi_camion_tms['nb_camions'] > 1
    ].head(20)
)

        VOYCLE  nb_camions
50013  8604279           2
53589  8638253           2

In [112]:
#verification pour les deux voyages sio ont voycle 8604279 et 
print(
    dfT[dfT['VOYCLE'].isin(['8604279', '8638253'])]
    [['VOYCLE', 'PLAMOTI']]
    .drop_duplicates()
)

         VOYCLE    PLAMOTI
175341  8604279  2591TU257
250687  8638253  8226TU215
290749  8604279  9858TU243
468685  8638253  CHFR_PARC

In [113]:
print(
    dfM[dfM['voycle'].isin(['8604279', '8638253'])]
    [['voycle', 'chauff', 'camion', 'date_idb', 'date_saisi', 'name_event']]
    .sort_values(['voycle', 'date_idb'])
)

Empty DataFrame
Columns: [voycle, chauff, camion, date_idb, date_saisi, name_event]
Index: []

In [114]:
print("la taille de la fichier tms",len(dfT))
print("la taille de la fichier mobility",len(dfM))

la taille de la fichier tms 493433
la taille de la fichier mobility 482470

In [115]:
df4 = pd.read_csv('tous les chauffeurs.csv', sep=';')

In [116]:
df4.head(20)

       CODE                     NOM SERVICE
0         7                 TEMP IT      LT
1       505       OUSSAMA FERCHICHI      LT
2       510           AMIR LASSOUED      LT
3   1000544          OUSSAMA KHFIFI      LT
4   1000544          OUSSAMA KHFIFI      LT
5    100508          BEN SAAD SALEM      LT
6    100537        RAYEN ABDELKADER      LT
7      1006          NASRALLI ADNEN      LT
8    100641             DAMERJI ALI      LT
9    100645              SASSI SAMI      LT
10  1011354           MOURAD ABIDLI      LT
11   101160             WAJDI HAJRI      LT
12   101161           HOUSSEM NSIRI      LT
13   101316            FAHMI FTOUHI      LT
14   101319          WISSEM HAMMADA      LT
15   101323  SOFIENNE BEN FATHALLAH      LT
16   101327            HAMDI MRABET      LT
17   101329          AHMED BEN AMOR      LT
18   101332      KARIM AOULED AHMED      LT
19   101336          MOHAMED RHAYEM      LT

In [117]:
df4.info

<bound method DataFrame.info of         CODE                   NOM SERVICE
0          7               TEMP IT      LT
1        505     OUSSAMA FERCHICHI      LT
2        510         AMIR LASSOUED      LT
3    1000544        OUSSAMA KHFIFI      LT
4    1000544        OUSSAMA KHFIFI      LT
..       ...                   ...     ...
385   TRP329   El Mokhtar ben rjab      EX
386   TRP330    MOUHAMED AZIZ RIFI      EX
387   TRP330   MOUHAMED AZIZ RIGHI      EX
388   TRP331            FAHMI MAKI      EX
389   TRP332  ABDERRAZAK EL GIZANI      EX

[390 rows x 3 columns]>

In [118]:
df4.isnull().sum()

CODE       0
NOM        0
SERVICE    0
dtype: int64

In [119]:
print(df4.columns.tolist())

['CODE', 'NOM', 'SERVICE']

In [120]:
df4.columns = df4.columns.str.strip()

In [121]:
print([col for col in df4.columns if 'SERVICE' in col.upper()])

['SERVICE']

In [122]:
print(len(df4))

390

In [123]:
print(df4['CODE'].nunique())

384

In [124]:
print("les valeurs duplique sont de le coe",df4['CODE'].value_counts())

les valeurs duplique sont de le coe CODE
373        2
1000544    2
TRP330     2
1432       2
1457       2
          ..
13143      1
13142      1
13141      1
13139      1
TRP332     1
Name: count, Length: 384, dtype: int64

In [125]:
print(
    df4[df4['CODE'].isin(['373', '1000544'])]
    [['CODE', 'NOM','SERVICE']]
    .drop_duplicates()
)

        CODE               NOM SERVICE
3    1000544    OUSSAMA KHFIFI      LT
220      373  BEN OTHMAN MAHER      LT

In [126]:
print(
    df4[df4['CODE'].isin(['TRP330', '1432'])]
    [['CODE', 'NOM','SERVICE']]
    .drop_duplicates()
)

       CODE                  NOM SERVICE
165    1432  MOUHAMED AZMI AYARI      LT
386  TRP330   MOUHAMED AZIZ RIFI      EX
387  TRP330  MOUHAMED AZIZ RIGHI      EX

In [127]:
print(df4['CODE'].duplicated().sum())
print(df4[df4['CODE'].duplicated(keep=False)])

6
        CODE                   NOM SERVICE
3    1000544        OUSSAMA KHFIFI      LT
4    1000544        OUSSAMA KHFIFI      LT
165     1432   MOUHAMED AZMI AYARI      LT
166     1432   MOUHAMED AZMI AYARI      LT
176     1457       Soltani chouaib      LT
177     1457      SOLTANI CHOUAIEB      LT
220      373      BEN OTHMAN MAHER      LT
221      373      BEN OTHMAN MAHER      LT
371   TRP316  ABDEJLIL BEN IBRAHIM      LT
372   TRP316        SALAH BOURAOUI      LT
386   TRP330    MOUHAMED AZIZ RIFI      EX
387   TRP330   MOUHAMED AZIZ RIGHI      EX

In [128]:
df4 = df4.drop_duplicates()

In [129]:
print("le nombre des lignes apres la suppression des doublons",len(df4))

le nombre des lignes apres la suppression des doublons 387

In [130]:
print(df4.duplicated().sum())

0

In [131]:
codes_dupliques = df4[
    df4.duplicated('CODE', keep=False)
].sort_values('CODE')

print(codes_dupliques)

       CODE                   NOM SERVICE
176    1457       Soltani chouaib      LT
177    1457      SOLTANI CHOUAIEB      LT
371  TRP316  ABDEJLIL BEN IBRAHIM      LT
372  TRP316        SALAH BOURAOUI      LT
386  TRP330    MOUHAMED AZIZ RIFI      EX
387  TRP330   MOUHAMED AZIZ RIGHI      EX

In [132]:
analyse_code = (
    df4.groupby('CODE')['NOM']
    .nunique()
    .sort_values(ascending=False)
)

print(analyse_code.head(20))

CODE
TRP330     2
1457       2
TRP316     2
1000544    1
412608     1
412660     1
412659     1
412658     1
412649     1
412642     1
412641     1
412636     1
412612     1
412599     1
417        1
412595     1
412587     1
412563     1
412547     1
412531     1
Name: NOM, dtype: int64

In [133]:
df4['NOM'] = (
    df4['NOM']
    .str.strip()
    .str.upper()
)

C:\Users\nourg\AppData\Local\Temp\ipykernel_7748\2772711591.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['NOM'] = (

In [134]:
codes_problematiques = (
    df4.groupby('CODE')['NOM']
    .nunique()
)

codes_problematiques = codes_problematiques[
    codes_problematiques > 1
]

print(codes_problematiques)

CODE
1457      2
TRP316    2
TRP330    2
Name: NOM, dtype: int64

In [135]:
df_a_verifier = df4[
    df4['CODE'].isin(codes_problematiques.index)
].sort_values('CODE')

print(df_a_verifier)

       CODE                   NOM SERVICE
176    1457       SOLTANI CHOUAIB      LT
177    1457      SOLTANI CHOUAIEB      LT
371  TRP316  ABDEJLIL BEN IBRAHIM      LT
372  TRP316        SALAH BOURAOUI      LT
386  TRP330    MOUHAMED AZIZ RIFI      EX
387  TRP330   MOUHAMED AZIZ RIGHI      EX

In [136]:
df4.loc[
    df4['CODE'] == '1457',
    'NOM'
] = 'SOLTANI CHOUAIEB'

In [137]:
df4 = df4.drop_duplicates()

In [138]:
print("le nombre des lignes apres la suppression des doublons",len(df4))

le nombre des lignes apres la suppression des doublons 386

In [139]:
dfM[dfM['chauff'].isin(['TRP316', 'TRP330'])][
    ['chauff', 'voycle','camion']
].drop_duplicates()

Empty DataFrame
Columns: [chauff, voycle, camion]
Index: []

In [140]:
#la verfication des deux codes dans tms
codes = ['TRP316']

resultat = dfT[dfT['PLACHA1I'].astype(str).isin(codes)][
    ['PLACHA1I', 'SALNOM', 'VOYCLE', 'VOYDTD']
].drop_duplicates()

print(resultat)

       PLACHA1I          SALNOM   VOYCLE                   VOYDTD
122366   TRP316  SALAH BOURAOUI  8649876  2026-05-19 00:00:00.000
122967   TRP316  SALAH BOURAOUI  8649778  2026-05-19 00:00:00.000
123434   TRP316  SALAH BOURAOUI  8658762  2026-05-21 00:00:00.000
124399   TRP316  SALAH BOURAOUI  8651380  2026-05-20 00:00:00.000
124804   TRP316  SALAH BOURAOUI  8657402  2026-05-22 00:00:00.000
...         ...             ...      ...                      ...
472906   TRP316  SALAH BOURAOUI  8785504  2026-06-19 00:00:00.000
472912   TRP316  SALAH BOURAOUI  8809558  2026-06-25 00:00:00.000
472914   TRP316  SALAH BOURAOUI  8807480  2026-06-25 00:00:00.000
473007   TRP316  SALAH BOURAOUI  8638031  2026-06-02 00:00:00.000
473008   TRP316  SALAH BOURAOUI  8638077  2026-06-09 00:00:00.000

[99 rows x 4 columns]

In [141]:
nom = ['ABDEJLIL BEN IBRAHIM']

resultat = dfT[
    dfT['SALNOM'].astype(str).str.strip().str.upper().isin(nom)
][
    ['PLACHA1I', 'SALNOM', 'VOYCLE', 'VOYDTD']
].drop_duplicates()

print(resultat)

Empty DataFrame
Columns: [PLACHA1I, SALNOM, VOYCLE, VOYDTD]
Index: []

In [142]:
nom = ['SALAH BOURAOUI']

resultat = dfT[
    dfT['SALNOM'].astype(str).str.strip().str.upper().isin(nom)
][
    ['PLACHA1I', 'SALNOM', 'VOYCLE', 'VOYDTD']
].drop_duplicates()

print(resultat)

       PLACHA1I          SALNOM   VOYCLE                   VOYDTD
107374   TRP326  SALAH BOURAOUI  8832095  2026-06-30 00:00:00.000
107449   TRP326  SALAH BOURAOUI  8832138  2026-06-30 00:00:00.000
118224   TRP326  SALAH BOURAOUI  8836537  2026-07-01 00:00:00.000
118734   TRP326  SALAH BOURAOUI  8842536  2026-07-02 00:00:00.000
122366   TRP316  SALAH BOURAOUI  8649876  2026-05-19 00:00:00.000
...         ...             ...      ...                      ...
472943   TRP326  SALAH BOURAOUI  8928538  2026-07-23 00:00:00.000
472947   TRP326  SALAH BOURAOUI  8935348  2026-07-23 00:00:00.000
472957   TRP326  SALAH BOURAOUI  8957746  2026-07-29 00:00:00.000
473007   TRP316  SALAH BOURAOUI  8638031  2026-06-02 00:00:00.000
473008   TRP316  SALAH BOURAOUI  8638077  2026-06-09 00:00:00.000

[172 rows x 4 columns]

In [143]:
nom = ['MOUHAMED AZIZ RIFI']

resultat = dfT[
    dfT['SALNOM'].astype(str).str.strip().str.upper().isin(nom)
][
    ['PLACHA1I', 'SALNOM', 'VOYCLE', 'VOYDTD']
].drop_duplicates()

print(resultat)

Empty DataFrame
Columns: [PLACHA1I, SALNOM, VOYCLE, VOYDTD]
Index: []

In [144]:
nom = ['MOUHAMED AZIZ RIGHI']

resultat = dfT[
    dfT['SALNOM'].astype(str).str.strip().str.upper().isin(nom)
][
    ['PLACHA1I', 'SALNOM', 'VOYCLE', 'VOYDTD']
].drop_duplicates()

print(resultat)

Empty DataFrame
Columns: [PLACHA1I, SALNOM, VOYCLE, VOYDTD]
Index: []

In [145]:
print(
    dfT[dfT['PLACHA1I'].astype(str).str.contains('TRP330', case=False, na=False)]
    ['PLACHA1I']
    .drop_duplicates()
)

Series([], Name: PLACHA1I, dtype: object)

In [146]:
dfT['PLACHA1I'] = (
    dfT['PLACHA1I']
    .astype(str)
    .str.strip()
    .str.upper()
)

In [147]:

codes = ['TRP330']

resultat = dfT[dfT['PLACHA1I'].astype(str).isin(codes)][
    ['PLACHA1I', 'SALNOM', 'VOYCLE', 'VOYDTD']
].drop_duplicates()

print(resultat)

Empty DataFrame
Columns: [PLACHA1I, SALNOM, VOYCLE, VOYDTD]
Index: []

In [148]:
df4['existe_dans_tms'] = df4['CODE'].astype(str).str.strip().str.upper().isin(
    dfT['PLACHA1I'].astype(str).str.strip().str.upper()
)

In [149]:
df4[df4['existe_dans_tms'] == False]

       CODE                            NOM SERVICE  existe_dans_tms
0         7                        TEMP IT      LT            False
202    2654                    SABER BAHRI      LT            False
203  300019      BALAAZI MOHAMED-CONVOYEUR      LT            False
204  300023                    MAKKI FAWZI      LT            False
296  736248                   BALAAZI ANIS      LT            False
297  736249                 LASSOUED FETHI      LT            False
312     932                    JBALI TAREK      LT            False
329  TRP161             ABDLAHMID MASMOUDI      EX            False
336  TRP251     SABER HARRABI - RTS GHARBI      EX            False
337  TRP256         JAMEL DAROUICHE - SATT      EX            False
338  TRP257              TAHER JOUINI-SATT      EX            False
346  TRP279  BACEM BEN HAMIDA - RTS GHARBI      EX            False
348  TRP284  OUSSEMA MCHITA - SOFIEN FEKIH      EX            False
352  TRP291                  KHALIL CHAIBI      EX            False
354  TRP295     MOUARD AMDOUNI -STE FGARBI      EX            False
357  TRP299   SAHBI BOU LAABA-WAHIB GHARBI      LT            False
386  TRP330             MOUHAMED AZIZ RIFI      EX            False
387  TRP330            MOUHAMED AZIZ RIGHI      EX            False
389  TRP332           ABDERRAZAK EL GIZANI      EX            False

In [150]:
df4[df4['existe_dans_tms'] == True]

        CODE                     NOM SERVICE  existe_dans_tms
1        505       OUSSAMA FERCHICHI      LT             True
2        510           AMIR LASSOUED      LT             True
3    1000544          OUSSAMA KHFIFI      LT             True
5     100508          BEN SAAD SALEM      LT             True
6     100537        RAYEN ABDELKADER      LT             True
..       ...                     ...     ...              ...
382   TRP326          SALAH BOURAOUI      LT             True
383   TRP327  OUSSAMA BEN ABDESSAMAD      LT             True
384   TRP328         MORTADHA AABIDI      EP             True
385   TRP329     EL MOKHTAR BEN RJAB      EX             True
388   TRP331              FAHMI MAKI      EX             True

[367 rows x 4 columns]

In [151]:
df4['statut_mobility'] = (
    df4['CODE'].astype(str).str.strip().str.upper()
    .isin(
        df['username'].astype(str).str.strip().str.upper()
    )
    .map({True: 'Existe', False: 'N_existe_pas'})
)

In [152]:
print(df4[['CODE', 'NOM', 'statut_mobility']].drop_duplicates())

        CODE                   NOM statut_mobility
0          7               TEMP IT          Existe
1        505     OUSSAMA FERCHICHI          Existe
2        510         AMIR LASSOUED          Existe
3    1000544        OUSSAMA KHFIFI          Existe
5     100508        BEN SAAD SALEM          Existe
..       ...                   ...             ...
385   TRP329   EL MOKHTAR BEN RJAB    N_existe_pas
386   TRP330    MOUHAMED AZIZ RIFI    N_existe_pas
387   TRP330   MOUHAMED AZIZ RIGHI    N_existe_pas
388   TRP331            FAHMI MAKI    N_existe_pas
389   TRP332  ABDERRAZAK EL GIZANI    N_existe_pas

[386 rows x 3 columns]

In [153]:
nb_chauffeurs = df4[df4['statut_mobility'] == 'Existe']['CODE'].nunique()

print("Nombre de chauffeurs existant dans Mobility :", nb_chauffeurs)

Nombre de chauffeurs existant dans Mobility : 293

In [154]:
nb_non_existants = df4[df4['statut_mobility'] == 'N_existe_pas']['CODE'].nunique()

print("Nombre de chauffeurs non existant dans Mobility :", nb_non_existants)

Nombre de chauffeurs non existant dans Mobility : 91

In [155]:
print(df4.groupby('statut_mobility')['CODE'].nunique())

statut_mobility
Existe          293
N_existe_pas     91
Name: CODE, dtype: int64

In [156]:
print("les differente type de service",df4['SERVICE'].value_counts())

les differente type de service SERVICE
LT    244
IN     75
EX     55
EP     11
SE      1
Name: count, dtype: int64

In [157]:
dfT.info()

<class 'pandas.core.frame.DataFrame'>
Index: 493433 entries, 0 to 494086
Data columns (total 27 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ARTCODE              493433 non-null  object
 1   CDATE                493433 non-null  object
 2   LIVRAISON            493433 non-null  object
 3   VOYCLE               493433 non-null  object
 4   PLALIB               493433 non-null  object
 5   PLAMOTI              493433 non-null  object
 6   SALNOM               493433 non-null  object
 7   PLACHA1I             493433 non-null  object
 8   TIECODE              493433 non-null  object
 9   VOYDTD               493433 non-null  object
 10  VOYHRD               493433 non-null  int64
 11  VOYDTF               493433 non-null  object
 12  VOYHRF               493433 non-null  int64
 13  VOYPAL               493433 non-null  float64
 14  SITESALARIE          493433 non-null  object
 15  SITECAMION           493433 non-null  object
 16  PLAKM2               493433 non-null  int64
 17  Deposant             493433 non-null  object
 18  OTSNUMBDX            493433 non-null  string
 19  Type_TRANSPORT       493433 non-null  object
 20  CAPACITE             493433 non-null  float64
 21  SITE_CHAUFFEUR       493433 non-null  object
 22  Type_Tourne         493433 non-null  object
 23  Type de marchandise  493433 non-null  object
 24  Temprature          493433 non-null  object
 25  SITE                 493433 non-null  object
 26  LIVRAISON_MANQUANTE  493433 non-null  bool
dtypes: bool(1), float64(2), int64(3), object(20), string(1)
memory usage: 102.1+ MB

In [158]:
print(dfT[['VOYDTD', 'VOYHRD', 'VOYDTF', 'VOYHRF']].head(10))

                    VOYDTD  VOYHRD                   VOYDTF  VOYHRF
0  2026-02-23 00:00:00.000     600  2026-02-23 00:00:00.000    1100
1  2026-02-21 00:00:00.000     500  2026-02-21 00:00:00.000    1300
2  2026-02-21 00:00:00.000     500  2026-02-21 00:00:00.000    1300
3  2026-02-10 00:00:00.000     600  2026-02-10 00:00:00.000    1500
4  2026-02-10 00:00:00.000     600  2026-02-10 00:00:00.000    1500
5  2026-02-10 00:00:00.000     600  2026-02-10 00:00:00.000    1500
6  2026-02-10 00:00:00.000     600  2026-02-10 00:00:00.000    1500
7  2026-02-10 00:00:00.000     630  2026-02-10 00:00:00.000    1530
8  2026-02-10 00:00:00.000     700  2026-02-10 00:00:00.000    1500
9  2026-02-10 00:00:00.000     700  2026-02-10 00:00:00.000    1500

In [159]:
dfT['VOYHRD'] = pd.to_datetime(
    dfT['VOYHRD'].astype(str).str.zfill(4),
    format='%H%M',
    errors='coerce'
)

dfT['VOYHRF'] = pd.to_datetime(
    dfT['VOYHRF'].astype(str).str.zfill(4),
    format='%H%M',
    errors='coerce'
)

In [160]:
dfT.info()

<class 'pandas.core.frame.DataFrame'>
Index: 493433 entries, 0 to 494086
Data columns (total 27 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ARTCODE              493433 non-null  object
 1   CDATE                493433 non-null  object
 2   LIVRAISON            493433 non-null  object
 3   VOYCLE               493433 non-null  object
 4   PLALIB               493433 non-null  object
 5   PLAMOTI              493433 non-null  object
 6   SALNOM               493433 non-null  object
 7   PLACHA1I             493433 non-null  object
 8   TIECODE              493433 non-null  object
 9   VOYDTD               493433 non-null  object
 10  VOYHRD               493433 non-null  datetime64[ns]
 11  VOYDTF               493433 non-null  object
 12  VOYHRF               493433 non-null  datetime64[ns]
 13  VOYPAL               493433 non-null  float64
 14  SITESALARIE          493433 non-null  object
 15  SITECAMION           493433 non-null  object
 16  PLAKM2               493433 non-null  int64
 17  Deposant             493433 non-null  object
 18  OTSNUMBDX            493433 non-null  string
 19  Type_TRANSPORT       493433 non-null  object
 20  CAPACITE             493433 non-null  float64
 21  SITE_CHAUFFEUR       493433 non-null  object
 22  Type_Tourne         493433 non-null  object
 23  Type de marchandise  493433 non-null  object
 24  Temprature          493433 non-null  object
 25  SITE                 493433 non-null  object
 26  LIVRAISON_MANQUANTE  493433 non-null  bool
dtypes: bool(1), datetime64[ns](2), float64(2), int64(1), object(20), string(1)
memory usage: 102.1+ MB

In [161]:
print(dfT[['VOYDTD', 'VOYHRD', 'VOYDTF', 'VOYHRF']].head(10))

                    VOYDTD              VOYHRD                   VOYDTF  \
0  2026-02-23 00:00:00.000 1900-01-01 06:00:00  2026-02-23 00:00:00.000
1  2026-02-21 00:00:00.000 1900-01-01 05:00:00  2026-02-21 00:00:00.000
2  2026-02-21 00:00:00.000 1900-01-01 05:00:00  2026-02-21 00:00:00.000
3  2026-02-10 00:00:00.000 1900-01-01 06:00:00  2026-02-10 00:00:00.000
4  2026-02-10 00:00:00.000 1900-01-01 06:00:00  2026-02-10 00:00:00.000
5  2026-02-10 00:00:00.000 1900-01-01 06:00:00  2026-02-10 00:00:00.000
6  2026-02-10 00:00:00.000 1900-01-01 06:00:00  2026-02-10 00:00:00.000
7  2026-02-10 00:00:00.000 1900-01-01 06:30:00  2026-02-10 00:00:00.000
8  2026-02-10 00:00:00.000 1900-01-01 07:00:00  2026-02-10 00:00:00.000
9  2026-02-10 00:00:00.000 1900-01-01 07:00:00  2026-02-10 00:00:00.000

               VOYHRF
0 1900-01-01 11:00:00
1 1900-01-01 13:00:00
2 1900-01-01 13:00:00
3 1900-01-01 15:00:00
4 1900-01-01 15:00:00
5 1900-01-01 15:00:00
6 1900-01-01 15:00:00
7 1900-01-01 15:30:00
8 1900-01-01 15:00:00
9 1900-01-01 15:00:00

In [162]:
dfT['CDATE'] = pd.to_datetime(dfT['CDATE'], errors='coerce')

dfT['VOYDTD'] = pd.to_datetime(dfT['VOYDTD'], errors='coerce')

dfT['VOYDTF'] = pd.to_datetime(dfT['VOYDTF'], errors='coerce')

In [163]:
print(dfT[['CDATE', 'VOYDTD', 'VOYDTF']].dtypes)

CDATE     datetime64[ns]
VOYDTD    datetime64[ns]
VOYDTF    datetime64[ns]
dtype: object

In [164]:
print(dfM[['date_idb', 'date_saisi']].dtypes)

date_idb      datetime64[ns]
date_saisi    datetime64[ns]
dtype: object

In [165]:
print(dfM.dtypes)

voycle                          object
chauff                          object
camion                          object
date_idb                datetime64[ns]
name_event                      object
date_saisi              datetime64[ns]
KM                              object
commentaire                     object
client                          object
next_destination                object
images                          object
time_event              datetime64[ns]
event_from                      object
tempurature                     object
SITE                            object
voyage_str                      object
nature_voyage                   object
delai_saisie_min               float64
categorie_remontee              object
delai_sai_even                 float64
time_event_manquante              bool
camion_tms                      object
dtype: object

In [166]:
print(dfM['KM'].head(20))
print(dfM['KM'].unique()[:20])

0     590305
1     590299
2     590299
3     590294
4     590294
5     590288
6          0
7     719508
8          0
9     293416
10    358317
11         0
12         0
13    629463
14         0
15         0
16    491731
17    558578
18    656178
19         0
Name: KM, dtype: object
[590305 590299 590294 590288 0 719508 293416 358317 629463 491731 558578
 656178 692562 468378 683083 908820 599485 522829 625893 394325]

In [167]:
dfM['KM'] = pd.to_numeric(dfM['KM'], errors='coerce')

In [168]:
print(dfM['KM'].dtype)

float64

In [169]:
print("Valeurs manquantes :", dfM['KM'].isna().sum())

Valeurs manquantes : 2

In [170]:
dfM[dfM['KM'] == 0][
    ['voycle', 'name_event', 'KM', 'date_idb', 'date_saisi']
].head(20)

      voycle  name_event   KM            date_idb          date_saisi
6    8190151  dep_client  0.0 2026-01-30 09:57:33 2026-01-30 09:57:00
8    8187245  dep_client  0.0 2026-01-30 09:57:57 2026-01-30 09:55:00
11   8188629  dep_client  0.0 2026-01-30 09:58:51 2026-01-30 09:58:00
12   8189621  arv_client  0.0 2026-01-30 09:58:55 2026-01-30 09:58:00
14   8190177  dep_client  0.0 2026-01-30 09:59:45 2026-01-30 09:59:00
15   8189253  dep_client  0.0 2026-01-30 09:59:51 2026-01-30 09:59:00
19   8190015  arv_client  0.0 2026-01-30 10:00:22 2026-01-30 10:00:00
20   8187587  dep_client  0.0 2026-01-30 10:00:42 2026-01-30 10:00:00
21   8189577  dep_client  0.0 2026-01-30 10:00:57 2026-01-30 10:00:00
23  8,19E+13  dep_client  0.0 2026-01-30 10:01:21 2026-01-30 10:01:00
24   8179331  dep_client  0.0 2026-01-30 10:01:30 2026-01-30 10:00:00
26   8190368  dep_client  0.0 2026-01-30 10:02:15 2026-01-30 10:02:00
27   8179076  dep_client  0.0 2026-01-30 10:02:16 2026-01-30 10:02:00
35   8189669  dep_client  0.0 2026-01-30 10:03:50 2026-01-30 10:03:00
37   8190241  dep_client  0.0 2026-01-30 10:04:21 2026-01-30 10:04:00
38   8187214  dep_client  0.0 2026-01-30 10:04:31 2026-01-30 10:04:00
41  8,19E+13  dep_client  0.0 2026-01-30 10:05:54 2026-01-30 10:05:00
44   8189669  dep_client  0.0 2026-01-30 10:06:05 2026-01-30 10:05:00
46   8190151  dep_client  0.0 2026-01-30 10:06:35 2026-01-30 10:06:00
48   8189298  dep_client  0.0 2026-01-30 10:07:11 2026-01-30 10:07:00

In [171]:
nb_zero = (dfM['KM'] == 0).sum()
nb_total = len(dfM)

print("Nombre de KM = 0 :", nb_zero)
print("Pourcentage :", round(nb_zero / nb_total * 100, 2), "%")

Nombre de KM = 0 : 201200
Pourcentage : 41.7 %

In [172]:
print("Nombre de lignes TMS :", len(dfT))

print("Nombre de voyages distincts :", dfT['VOYCLE'].nunique())

print("Nombre de VOYCLE dupliqués :", dfT['VOYCLE'].duplicated().sum())

Nombre de lignes TMS : 493433
Nombre de voyages distincts : 86957
Nombre de VOYCLE dupliqués : 406476

In [173]:
# Nombre de lignes par VOYCLE
nb_lignes_par_voyage = dfT.groupby('VOYCLE').size()

print("Nombre moyen de lignes par voyage :", nb_lignes_par_voyage.mean())
print("Nombre minimum :", nb_lignes_par_voyage.min())
print("Nombre maximum :", nb_lignes_par_voyage.max())

print("\nRépartition du nombre de lignes par voyage :")
print(nb_lignes_par_voyage.describe())

Nombre moyen de lignes par voyage : 5.674448290534402
Nombre minimum : 1
Nombre maximum : 74

Répartition du nombre de lignes par voyage :
count    86957.000000
mean         5.674448
std          7.197664
min          1.000000
25%          1.000000
50%          3.000000
75%          7.000000
max         74.000000
dtype: float64

In [174]:
print(dfT.columns.tolist())

['ARTCODE', 'CDATE', 'LIVRAISON', 'VOYCLE', 'PLALIB', 'PLAMOTI', 'SALNOM', 'PLACHA1I', 'TIECODE', 'VOYDTD', 'VOYHRD', 'VOYDTF', 'VOYHRF', 'VOYPAL', 'SITESALARIE', 'SITECAMION', 'PLAKM2', 'Deposant', 'OTSNUMBDX', 'Type_TRANSPORT', 'CAPACITE', 'SITE_CHAUFFEUR', 'Type_Tourn\x8ee', 'Type de marchandise', 'Temp\x8erature', 'SITE', 'LIVRAISON_MANQUANTE']

In [175]:
print("Nombre de OTSNUMBDX distincts :", dfT['OTSNUMBDX'].nunique())

print("Nombre de OTSNUMBDX dupliqués :",
      dfT['OTSNUMBDX'].duplicated().sum())

Nombre de OTSNUMBDX distincts : 422285
Nombre de OTSNUMBDX dupliqués : 71148

In [176]:
refs_par_voyage = dfT.groupby('VOYCLE')['OTSNUMBDX'].nunique()

print("Nombre moyen de références par voyage :", refs_par_voyage.mean())
print("Minimum :", refs_par_voyage.min())
print("Maximum :", refs_par_voyage.max())

print("\nStatistiques :")
print(refs_par_voyage.describe())

Nombre moyen de références par voyage : 5.393125337810642
Minimum : 1
Maximum : 74

Statistiques :
count    86957.000000
mean         5.393125
std          7.202682
min          1.000000
25%          1.000000
50%          2.000000
75%          6.000000
max         74.000000
Name: OTSNUMBDX, dtype: float64

In [177]:
print(
    dfT[['VOYCLE', 'PLALIB', 'OTSNUMBDX']]
    .sort_values('VOYCLE')
    .head(30)
)

         VOYCLE                         PLALIB        OTSNUMBDX
68170   7074462              TRANSPORT AMBIANT  CD2505-BRA10875
3407    7104246              TRANSPORT AMBIANT  CD2505-BRA11530
268326  7676168         TRANSPORT MISSION PARC    NON_RENSEIGNE
357052  7937382         TRANSPORT MISSION PARC       DIV0003871
268327  7937383         TRANSPORT MISSION PARC       DIV0003872
468411  7937384         TRANSPORT MISSION PARC       DIV0003873
268328  7941008         TRANSPORT MISSION PARC       DIV0003959
35191   8000248     TRANSPORT CONTRLé // 12¡C  CD2512-PBH60121
268329  8050959         TRANSPORT MISSION PARC       DIV0006498
398997  8050960  TRANSFERT INTER DEPOT FACTURE       DIV0006499
455051  8050961  TRANSFERT INTER DEPOT FACTURE       DIV0006500
468412  8050966         TRANSPORT MISSION PARC       DIV0006492
357075  8062950         TRANSPORT MISSION PARC       DIV0005912
268330  8066378         TRANSPORT MISSION PARC       DIV0006927
268331  8066383         TRANSPORT MISSION PARC       DIV0006932
468413  8066384         TRANSPORT MISSION PARC       DIV0006933
268332  8067326         TRANSPORT MISSION PARC       DIV0003760
268333  8067327         TRANSPORT MISSION PARC       DIV0003869
312506  8067703   TRANSPORT INTER DEPOT ANNEXE       DIV0006992
279994  8067705   TRANSPORT INTER DEPOT ANNEXE       DIV0006994
268334  8068000         TRANSPORT MISSION PARC       DIV0003870
276057  8068341         TRANSPORT MISSION PARC    NON_RENSEIGNE
3408    8076260              TRANSPORT AMBIANT  CD2512-MEN65158
36624   8076753              TRANSPORT AMBIANT           563444
279995  8079125   TRANSPORT INTER DEPOT ANNEXE       DIV0007195
279996  8079137   TRANSPORT INTER DEPOT ANNEXE       DIV0007208
248577  8079138            TRANSPORT TECHNIQUE       DIV0007209
276447  8079139   TRANSPORT INTER DEPOT ANNEXE       DIV0007210
468825  8079140   TRANSPORT INTER DEPOT ANNEXE       DIV0007211
3497    8081240              TRANSPORT AMBIANT  CD2512-PBH64249

In [178]:
colonnes_a_verifier = [
    'VOYCLE',
    'VOYDTD',
    'VOYHRD',
    'VOYDTF',
    'VOYHRF',
    'PLALIB',
    'PLAMOTI',
    'SALNOM',
    'PLACHA1I',
    'SITESALARIE',
    'SITECAMION',
    'SITE_CHAUFFEUR',
    'SITE',
    'Type_TRANSPORT',
    'Type_Tourn\x8ee',
    'OTSNUMBDX'
]

for col in colonnes_a_verifier:
    print(f"\n===== {col} =====")
    print(dfT[col].head(5).tolist())
    print("Nombre de valeurs distinctes :", dfT[col].nunique())

===== VOYCLE =====
['8289736', '8289956', '8289956', '8235406', '8235406']
Nombre de valeurs distinctes : 86957

===== VOYDTD =====
[Timestamp('2026-02-23 00:00:00'), Timestamp('2026-02-21 00:00:00'), Timestamp('2026-02-21 00:00:00'), Timestamp('2026-02-10 00:00:00'), Timestamp('2026-02-10 00:00:00')]
Nombre de valeurs distinctes : 219

===== VOYHRD =====
[Timestamp('1900-01-01 06:00:00'), Timestamp('1900-01-01 05:00:00'), Timestamp('1900-01-01 05:00:00'), Timestamp('1900-01-01 06:00:00'), Timestamp('1900-01-01 06:00:00')]
Nombre de valeurs distinctes : 861

===== VOYDTF =====
[Timestamp('2026-02-23 00:00:00'), Timestamp('2026-02-21 00:00:00'), Timestamp('2026-02-21 00:00:00'), Timestamp('2026-02-10 00:00:00'), Timestamp('2026-02-10 00:00:00')]
Nombre de valeurs distinctes : 234

===== VOYHRF =====
[Timestamp('1900-01-01 11:00:00'), Timestamp('1900-01-01 13:00:00'), Timestamp('1900-01-01 13:00:00'), Timestamp('1900-01-01 15:00:00'), Timestamp('1900-01-01 15:00:00')]
Nombre de valeurs distinctes : 902

===== PLALIB =====
['TRANSPORT AMBIANT', 'TRANSPORT AMBIANT', 'TRANSPORT AMBIANT', 'TRANSPORT AMBIANT', 'TRANSPORT AMBIANT']
Nombre de valeurs distinctes : 31

===== PLAMOTI =====
['9471TU205', '527TU174', '527TU174', '8564TU232', '8564TU232']
Nombre de valeurs distinctes : 311

===== SALNOM =====
['BEN BRAHIM ABDELKADER', 'TALEB SAMI', 'TALEB SAMI', 'BEL HASSEN MOEZ', 'BEL HASSEN MOEZ']
Nombre de valeurs distinctes : 396

===== PLACHA1I =====
['418', '428', '428', '411', '411']
Nombre de valeurs distinctes : 399

===== SITESALARIE =====
['BAR', 'GAS', 'GAS', 'BAR', 'BAR']
Nombre de valeurs distinctes : 14

===== SITECAMION =====
['BAR', 'GAS', 'GAS', 'BAR', 'BAR']
Nombre de valeurs distinctes : 13

===== SITE_CHAUFFEUR =====
['BAR', 'GAF', 'GAF', 'BAR', 'BAR']
Nombre de valeurs distinctes : 13

===== SITE =====
['BAR', 'GAF', 'GAF', 'BAR', 'BAR']
Nombre de valeurs distinctes : 12

===== Type_TRANSPORT =====
['LT', 'LT', 'LT', 'LT', 'LT']
Nombre de valeurs distinctes : 3

===== Type_Tourne =====
['Factur\x8ee', 'Factur\x8ee', 'Factur\x8ee', 'Factur\x8ee', 'Factur\x8ee']
Nombre de valeurs distinctes : 3

===== OTSNUMBDX =====
['DIV0013362', 'CD2602-PGF08443', 'CD2602-PGF08383', 'CD2602-CBR04738', 'CD2602-CBR04807']
Nombre de valeurs distinctes : 422285

In [179]:
controle = dfT.groupby('VOYCLE').agg(
    chauffeurs=('PLACHA1I', 'nunique'),
    camions=('PLAMOTI', 'nunique'),
    sites=('SITE', 'nunique'),
    types_tournee=('Type_Tourn\x8ee', 'nunique'),
    types_transport=('Type_TRANSPORT', 'nunique')
)

print("Voyages avec plusieurs chauffeurs :", 
      (controle['chauffeurs'] > 1).sum())

print("Voyages avec plusieurs camions :", 
      (controle['camions'] > 1).sum())

print("Voyages avec plusieurs sites :", 
      (controle['sites'] > 1).sum())

print("Voyages avec plusieurs types de tournée :", 
      (controle['types_tournee'] > 1).sum())

print("Voyages avec plusieurs types de transport :", 
      (controle['types_transport'] > 1).sum())

Voyages avec plusieurs chauffeurs : 2
Voyages avec plusieurs camions : 2
Voyages avec plusieurs sites : 0
Voyages avec plusieurs types de tournée : 2
Voyages avec plusieurs types de transport : 0

In [180]:
print("Date minimale :", dfT['VOYDTD'].min())
print("Date maximale :", dfT['VOYDTD'].max())
print("Nombre de dates distinctes :", dfT['VOYDTD'].nunique())

Date minimale : 2026-01-01 00:00:00
Date maximale : 2026-08-28 00:00:00
Nombre de dates distinctes : 219

In [181]:
# Copie du TMS
dfT_clean = dfT.copy()

# --------------------------------------------------
# 1. Nettoyage de VOYCLE
# --------------------------------------------------
dfT_clean['VOYCLE'] = dfT_clean['VOYCLE'].astype(str).str.strip()

# --------------------------------------------------
# 2. Nettoyage des références de commande
# --------------------------------------------------
dfT_clean['OTSNUMBDX'] = (
    dfT_clean['OTSNUMBDX']
    .astype(str)
    .str.strip()
)

# Les valeurs non renseignées ne doivent pas être comptées
dfT_clean.loc[
    dfT_clean['OTSNUMBDX'].isin(['NON_RENSEIGNE', 'nan', '', 'None']),
    'OTSNUMBDX'
] = np.nan

# --------------------------------------------------
# 3. Trier les données
# --------------------------------------------------
dfT_clean = dfT_clean.sort_values(
    ['VOYCLE', 'VOYDTD', 'VOYHRD']
)

# --------------------------------------------------
# 4. Une ligne = un voyage
# --------------------------------------------------
dfT_voyage = dfT_clean.groupby('VOYCLE').agg(

    date_depart=('VOYDTD', 'first'),
    heure_depart=('VOYHRD', 'first'),

    date_fin=('VOYDTF', 'first'),
    heure_fin=('VOYHRF', 'first'),

    id_chauffeur=('PLACHA1I', 'first'),
    nom_chauffeur=('SALNOM', 'first'),

    id_camion=('PLAMOTI', 'first'),
    capacite=('CAPACITE', 'first'),

    site=('SITE', 'first'),
    site_chauffeur=('SITE_CHAUFFEUR', 'first'),
    site_camion=('SITECAMION', 'first'),

    type_voyage=('Type_Tourn\x8ee', 'first'),
    type_transport=('Type_TRANSPORT', 'first'),

    nb_references=('OTSNUMBDX', 'nunique')

).reset_index()

# --------------------------------------------------
# 5. Vérification
# --------------------------------------------------
print("Nombre de voyages :", len(dfT_voyage))
print("Nombre de VOYCLE uniques :", dfT_voyage['VOYCLE'].nunique())

print("\nAperçu :")
display(dfT_voyage.head())

Nombre de voyages : 86957
Nombre de VOYCLE uniques : 86957

Aperçu :

,VOYCLE,date_depart,heure_depart,date_fin,heure_fin,id_chauffeur,nom_chauffeur,id_camion,capacite,site,site_chauffeur,site_camion,type_voyage,type_transport,nb_references
0,7074462,2026-04-23,1900-01-01 07:00:00,2026-04-23,1900-01-01 08:00:00,52,ABDELAOUI RAMZI,900TU184,23.0,BAR,BAR,BAR,Facture,LT,1
1,7104246,2026-04-23,1900-01-01 07:00:00,2026-04-23,1900-01-01 08:00:00,664,BEN SMIDA ANIS,901TU184,23.0,BAR,BAR,BAR,Facture,LT,1
2,7676168,2026-01-12,1900-01-01 22:00:00,2026-01-13,1900-01-01 06:00:00,62,LASSOUED MOHAMED,CHFR_PARC,10.0,BAR,BAR,BAR,Mission,LT,0
3,7937382,2026-01-15,1900-01-01 22:00:00,2026-01-16,1900-01-01 06:00:00,300637,YEZIDI SLEH EDDINE,CHFR_PARC,10.0,BAR,BAR,BAR,Mission,LT,1
4,7937383,2026-01-20,1900-01-01 22:00:00,2026-01-21,1900-01-01 06:00:00,1106,RMILI KAMEL,CHFR_PARC,10.0,BAR,BAR,BAR,Mission,LT,1

In [182]:
print(dfM.columns.tolist())

['voycle', 'chauff', 'camion', 'date_idb', 'name_event', 'date_saisi', 'KM', 'commentaire', 'client', 'next_destination', 'images', 'time_event', 'event_from', 'tempurature', 'SITE', 'voyage_str', 'nature_voyage', 'delai_saisie_min', 'categorie_remontee', 'delai_sai_even', 'time_event_manquante', 'camion_tms']

In [183]:
# Copie de Mobility
dfM_clean = dfM.copy()

# --------------------------------------------------
# 1. Nettoyage de la clé VOYCLE
# --------------------------------------------------
dfM_clean['voycle'] = (
    dfM_clean['voycle']
    .astype(str)
    .str.strip()
)

# Supprimer les VOYCLE non renseignés
dfM_clean = dfM_clean[
    ~dfM_clean['voycle'].isin(['nan', 'None', '', 'NaN'])
]

# --------------------------------------------------
# 2. Agrégation au niveau voyage
# --------------------------------------------------
dfM_voyage = dfM_clean.groupby('voycle').agg(
    nb_evenements=('voycle', 'size'),
    nb_evenements_sans_temps=('time_event_manquante', 'sum'),
    delai_saisie_moyen=('delai_saisie_min', 'mean')
).reset_index()

# --------------------------------------------------
# 3. Présence dans Mobility
# --------------------------------------------------
dfM_voyage['present_mobility'] = 1

# --------------------------------------------------
# 4. Voyage sans événement
# --------------------------------------------------
dfM_voyage['voyage_sans_evenement'] = 0

print("Nombre de voyages Mobility :", len(dfM_voyage))

display(dfM_voyage.head())

Nombre de voyages Mobility : 58813

,voycle,nb_evenements,nb_evenements_sans_temps,delai_saisie_moyen,present_mobility,voyage_sans_evenement
0,"8,09E+13",16,0,3.671875,1,0
1,"8,11E+13",10,2,441.150000,1,0
2,"8,12E+13",2,0,0.300000,1,0
3,"8,13E+13",24,0,236.672917,1,0
4,"8,14E+13",24,7,694.236806,1,0

In [184]:
print("Type VOYCLE TMS :", dfT_voyage['VOYCLE'].dtype)
print("Type VOYCLE Mobility :", dfM_voyage['voycle'].dtype)

print("\nQuelques VOYCLE TMS :")
print(dfT_voyage['VOYCLE'].head(10).tolist())

print("\nQuelques VOYCLE Mobility :")
print(dfM_voyage['voycle'].head(10).tolist())

Type VOYCLE TMS : object
Type VOYCLE Mobility : object

Quelques VOYCLE TMS :
['7074462', '7104246', '7676168', '7937382', '7937383', '7937384', '7941008', '8000248', '8050959', '8050960']

Quelques VOYCLE Mobility :
['8,09E+13', '8,11E+13', '8,12E+13', '8,13E+13', '8,14E+13', '8,15E+13', '8,16E+13', '8,17E+13', '8,17E+20', '8,18E+13']

In [185]:
# Longueur des VOYCLE dans Mobility
print("Répartition de la longueur des VOYCLE Mobility :")
print(
    dfM_voyage['voycle']
    .str.len()
    .value_counts()
    .sort_index()
)

print("\nQuelques VOYCLE Mobility avec une longueur <= 10 :")
print(
    dfM_voyage[
        dfM_voyage['voycle'].str.len() <= 10
    ]['voycle'].head(30).tolist()
)

print("\nQuelques VOYCLE Mobility avec une longueur > 10 :")
print(
    dfM_voyage[
        dfM_voyage['voycle'].str.len() > 10
    ]['voycle'].head(30).tolist()
)

Répartition de la longueur des VOYCLE Mobility :
voycle
7    58719
8       94
Name: count, dtype: int64

Quelques VOYCLE Mobility avec une longueur <= 10 :
['8,09E+13', '8,11E+13', '8,12E+13', '8,13E+13', '8,14E+13', '8,15E+13', '8,16E+13', '8,17E+13', '8,17E+20', '8,18E+13', '8,19E+13', '8,20E+13', '8,21E+13', '8,22E+13', '8,23E+13', '8,24E+13', '8,25E+13', '8,26E+13', '8,27E+13', '8,28E+13', '8,29E+13', '8,30E+13', '8,31E+13', '8,32E+13', '8,33E+13', '8,34E+13', '8,35E+13', '8,36E+13', '8,37E+13', '8,38E+13']

Quelques VOYCLE Mobility avec une longueur > 10 :
[]

In [186]:
print("Exemples dans dfM original :")
print(
    dfM[['voycle', 'chauff', 'camion']]
    .head(30)
    .to_string(index=False)
)

Exemples dans dfM original :
  voycle chauff    camion
 8120158    120 6154TU201
 8120158    120 6154TU201
 8119945    120 6154TU201
 8119945    120 6154TU201
 8119466    120 6154TU201
 8119466    120 6154TU201
 8190151  13136 1185TU202
 8190127   1067 8822TU197
 8187245  13120 8572TU204
 8189632     84 4963TU204
 8186139 300377 8332TU215
 8188629 412362 5084TU198
 8189621    411 8564TU232
 8187210    120 2713TU210
 8190177 TRP136 9300TU199
 8189253 412385 2820TU173
 8188629 412362 5084TU198
 8186166  13156 2169TU181
 8190151  13136 1185TU202
 8190015  13104 7580TU181
 8187587  13148 2156TU174
 8189577    410  159TU215
 8187191   1125 5086TU198
8,19E+13    111 5012TU182
 8179331 101349 2771TU229
 8191856  13087 1188TU202
 8190368 Trp166 9386TU231
 8179076   1006 6704TU223
 8187187   1392  966TU216
 8189058    664  901TU184

In [187]:
# VOYCLE Mobility sous forme texte
dfM_clean['voycle'] = (
    dfM_clean['voycle']
    .astype(str)
    .str.strip()
)

# VOYCLE valides : exactement 7 chiffres
mask_voycle_valide = dfM_clean['voycle'].str.fullmatch(r'\d{7}')

print("VOYCLE Mobility valides :", mask_voycle_valide.sum())
print("VOYCLE Mobility invalides :", (~mask_voycle_valide).sum())

print("\nExemples de VOYCLE invalides :")
print(
    dfM_clean.loc[~mask_voycle_valide, 'voycle']
    .drop_duplicates()
    .head(30)
    .tolist()
)

VOYCLE Mobility valides : 477862
VOYCLE Mobility invalides : 4608

Exemples de VOYCLE invalides :
['8,19E+13', '8,11E+13', '8,12E+13', '8,09E+13', '8,18E+13', '8,16E+13', '8,14E+13', '8,20E+13', '8,15E+13', '8,17E+13', '8,13E+13', '8,21E+13', '8,31E+13', '8,17E+20', '8,25E+13', '8,24E+13', '8,26E+13', '8,22E+13', '8,27E+13', '8,29E+13', '8,23E+13', '8,46E+13', '8,33E+13', '8,37E+13', '8,30E+13', '8,28E+13', '8,32E+13', '8,34E+13', '8,35E+13', '8,50E+13']

In [188]:
# Vérifier combien de VOYCLE Mobility valides existent réellement dans le TMS
voycles_tms = set(dfT_voyage['VOYCLE'].astype(str))

voycles_mobility_valides = set(
    dfM_clean.loc[mask_voycle_valide, 'voycle']
)

voycles_communs = voycles_tms.intersection(
    voycles_mobility_valides
)

print("Voyages TMS :", len(voycles_tms))
print("Voyages Mobility valides :", len(voycles_mobility_valides))
print("Voyages présents dans les deux :", len(voycles_communs))
print("Voyages Mobility non trouvés dans TMS :",
      len(voycles_mobility_valides - voycles_tms))

Voyages TMS : 86957
Voyages Mobility valides : 58719
Voyages présents dans les deux : 58121
Voyages Mobility non trouvés dans TMS : 598

In [189]:
# Garder uniquement les VOYCLE Mobility valides
dfM_valid = dfM_clean[
    dfM_clean['voycle'].str.fullmatch(r'\d{7}', na=False)
].copy()

# Agrégation Mobility au niveau VOYCLE
dfM_voyage = dfM_valid.groupby('voycle').agg(
    nb_evenements=('voycle', 'size'),
    nb_evenements_sans_temps=('time_event_manquante', 'sum'),
    delai_saisie_moyen=('delai_saisie_min', 'mean')
).reset_index()

# Présence dans Mobility
dfM_voyage['present_mobility'] = 1

print("Voyages Mobility après nettoyage :", len(dfM_voyage))

Voyages Mobility après nettoyage : 58719

In [190]:
Fact_Voyage = dfT_voyage.merge(
    dfM_voyage,
    left_on='VOYCLE',
    right_on='voycle',
    how='left'
)

# Supprimer la colonne Mobility utilisée pour le rapprochement
Fact_Voyage.drop(columns=['voycle'], inplace=True)


# Voyages absents de Mobility


Fact_Voyage['present_mobility'] = (
    Fact_Voyage['present_mobility']
    .fillna(0)
    .astype(int)
)

Fact_Voyage['nb_evenements'] = (
    Fact_Voyage['nb_evenements']
    .fillna(0)
    .astype(int)
)

Fact_Voyage['nb_evenements_sans_temps'] = (
    Fact_Voyage['nb_evenements_sans_temps']
    .fillna(0)
    .astype(int)
)

Fact_Voyage['voyage_sans_evenement'] = (
    Fact_Voyage['present_mobility'] == 0
).astype(int)

print("Nombre de lignes Fact_Voyage :", len(Fact_Voyage))

print(
    Fact_Voyage['present_mobility']
    .value_counts()
)

Nombre de lignes Fact_Voyage : 86957
present_mobility
1    58121
0    28836
Name: count, dtype: int64

In [191]:
print("Voyages Fact_Voyage :", len(Fact_Voyage))
print("VOYCLE uniques :", Fact_Voyage['VOYCLE'].nunique())

print("\nPrésence Mobility :")
print(
    Fact_Voyage['present_mobility']
    .value_counts()
)

print("\nNombre de voyages sans événement :",
      Fact_Voyage['voyage_sans_evenement'].sum())

Voyages Fact_Voyage : 86957
VOYCLE uniques : 86957

Présence Mobility :
present_mobility
1    58121
0    28836
Name: count, dtype: int64

Nombre de voyages sans événement : 28836

In [192]:
Fact_Voyage['nb_anomalies'] = (
    Fact_Voyage['nb_evenements_sans_temps']
)

print(Fact_Voyage[
    [
        'VOYCLE',
        'nb_references',
        'present_mobility',
        'nb_evenements',
        'nb_evenements_sans_temps',
        'delai_saisie_moyen',
        'voyage_sans_evenement',
        'nb_anomalies'
    ]
].head(10))

    VOYCLE  nb_references  present_mobility  nb_evenements  \
0  7074462              1                 0              0
1  7104246              1                 0              0
2  7676168              0                 0              0
3  7937382              1                 0              0
4  7937383              1                 0              0
5  7937384              1                 0              0
6  7941008              1                 0              0
7  8000248              1                 0              0
8  8050959              1                 0              0
9  8050960              1                 0              0

   nb_evenements_sans_temps  delai_saisie_moyen  voyage_sans_evenement  \
0                         0                 NaN                      1
1                         0                 NaN                      1
2                         0                 NaN                      1
3                         0                 NaN                      1
4                         0                 NaN                      1
5                         0                 NaN                      1
6                         0                 NaN                      1
7                         0                 NaN                      1
8                         0                 NaN                      1
9                         0                 NaN                      1

   nb_anomalies
0             0
1             0
2             0
3             0
4             0
5             0
6             0
7             0
8             0
9             0

In [193]:
print("========== CONTROLE FINAL ==========")

print("Nombre de lignes :", len(Fact_Voyage))
print("VOYCLE uniques :", Fact_Voyage['VOYCLE'].nunique())

print("\nPrésence Mobility :")
print(Fact_Voyage['present_mobility'].value_counts())

print("\nVoyages sans Mobility :",
      Fact_Voyage['voyage_sans_evenement'].sum())

print("\nNombre total d'événements Mobility :",
      Fact_Voyage['nb_evenements'].sum())

print("\nNombre total d'événements sans heure :",
      Fact_Voyage['nb_evenements_sans_temps'].sum())

print("\nNombre total d'anomalies :",
      Fact_Voyage['nb_anomalies'].sum())

print("\nNombre de références :",
      Fact_Voyage['nb_references'].sum())

========== CONTROLE FINAL ==========
Nombre de lignes : 86957
VOYCLE uniques : 86957

Présence Mobility :
present_mobility
1    58121
0    28836
Name: count, dtype: int64

Voyages sans Mobility : 28836

Nombre total d'événements Mobility : 475224

Nombre total d'événements sans heure : 12796

Nombre total d'anomalies : 12796

Nombre de références : 465931

In [194]:
print("les noms de colonnes de la fichier user_mobility",df.columns)
print("les noms de colonnes de la fichier tous_chauffeurs",df4.columns)
print("les noms de colonnes de la fichier TMS",dfT.columns)
print("les noms de colonnes de la fichier mobility",dfM.columns)

les noms de colonnes de la fichier user_mobility Index(['username', 'display_name'], dtype='object')
les noms de colonnes de la fichier tous_chauffeurs Index(['CODE', 'NOM', 'SERVICE', 'existe_dans_tms', 'statut_mobility'], dtype='object')
les noms de colonnes de la fichier TMS Index(['ARTCODE', 'CDATE', 'LIVRAISON', 'VOYCLE', 'PLALIB', 'PLAMOTI',
       'SALNOM', 'PLACHA1I', 'TIECODE', 'VOYDTD', 'VOYHRD', 'VOYDTF', 'VOYHRF',
       'VOYPAL', 'SITESALARIE', 'SITECAMION', 'PLAKM2', 'Deposant',
       'OTSNUMBDX', 'Type_TRANSPORT', 'CAPACITE', 'SITE_CHAUFFEUR',
       'Type_Tourne', 'Type de marchandise', 'Temprature', 'SITE',
       'LIVRAISON_MANQUANTE'],
      dtype='object')
les noms de colonnes de la fichier mobility Index(['voycle', 'chauff', 'camion', 'date_idb', 'name_event', 'date_saisi',
       'KM', 'commentaire', 'client', 'next_destination', 'images',
       'time_event', 'event_from', 'tempurature', 'SITE', 'voyage_str',
       'nature_voyage', 'delai_saisie_min', 'categorie_remontee',
       'delai_sai_even', 'time_event_manquante', 'camion_tms'],
      dtype='object')

In [195]:
!pip install sqlalchemy pyodbc

Requirement already satisfied: sqlalchemy in c:\users\nourg\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pyodbc in c:\users\nourg\anaconda3\lib\site-packages (5.3.0)
Requirement already satisfied: greenlet>=1 in c:\users\nourg\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\nourg\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [196]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

In [197]:
import pyodbc

server = r"localhost\SQLEXPRESS"

conn = pyodbc.connect(
    f"DRIVER={{ODBC Driver 17 for SQL Server}};"
    f"SERVER={server};"
    f"Trusted_Connection=yes;"
    f"TrustServerCertificate=yes;"
)

print("✅ Connexion SQL Server réussie !")

conn.close()

✅ Connexion SQL Server réussie !

In [198]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

server = r"localhost\SQLEXPRESS"
database = "staging_systemeTransport"

connection_string = (
    f"DRIVER={{ODBC Driver 17 for SQL Server}};"
    f"SERVER={server};"
    f"DATABASE={database};"
    f"Trusted_Connection=yes;"
    f"TrustServerCertificate=yes;"
)

engine = create_engine(
    "mssql+pyodbc:///?odbc_connect=" + quote_plus(connection_string),
    fast_executemany=True,
    use_insertmanyvalues=False
)

print(" Engine créé avec fast_executemany")

 Engine créé avec fast_executemany

In [199]:
dfT_stg = dfT.copy()

dfT_stg = dfT_stg.rename(columns={
    'Type_Tourn\x8ee': 'Type_Tournee',
    'Type de marchandise': 'Type_marchandise',
    'Temp\x8erature': 'Temperature'
})

In [200]:
print(dfT_stg.columns.tolist())

['ARTCODE', 'CDATE', 'LIVRAISON', 'VOYCLE', 'PLALIB', 'PLAMOTI', 'SALNOM', 'PLACHA1I', 'TIECODE', 'VOYDTD', 'VOYHRD', 'VOYDTF', 'VOYHRF', 'VOYPAL', 'SITESALARIE', 'SITECAMION', 'PLAKM2', 'Deposant', 'OTSNUMBDX', 'Type_TRANSPORT', 'CAPACITE', 'SITE_CHAUFFEUR', 'Type_Tournee', 'Type_marchandise', 'Temperature', 'SITE', 'LIVRAISON_MANQUANTE']

In [201]:
dfT_stg['CDATE'] = pd.to_datetime(dfT_stg['CDATE'], errors='coerce')
dfT_stg['VOYDTD'] = pd.to_datetime(dfT_stg['VOYDTD'], errors='coerce')
dfT_stg['VOYDTF'] = pd.to_datetime(dfT_stg['VOYDTF'], errors='coerce')

In [202]:
dfT_stg['VOYHRD'] = pd.to_datetime(
    dfT_stg['VOYHRD'], errors='coerce'
).dt.time

dfT_stg['VOYHRF'] = pd.to_datetime(
    dfT_stg['VOYHRF'], errors='coerce'
).dt.time

In [203]:
print(len(dfT_stg))

493433

In [204]:
#77777777777777777777
# Chargement optimisé dans la table STG_TMS

"""
dfT_stg.to_sql(
    name='STG_TMS',
    con=engine,
    schema='dbo',
    if_exists='append',  # ou 'replace' pour récréer la table
    index=False,
    chunksize=1000
)
print("Données insérées avec succès via to_sql !")
"""

'\ndfT_stg.to_sql(\n    name=\'STG_TMS\',\n    con=engine,\n    schema=\'dbo\',\n    if_exists=\'append\',  # ou \'replace\' pour récréer la table\n    index=False,\n    chunksize=1000\n)\nprint("Données insérées avec succès via to_sql !")\n'

In [205]:
dfM_stg = dfM.copy()

In [206]:
dfM_stg['date_idb'] = pd.to_datetime(
    dfM_stg['date_idb'], errors='coerce'
)

dfM_stg['date_saisi'] = pd.to_datetime(
    dfM_stg['date_saisi'], errors='coerce'
)

dfM_stg['time_event'] = pd.to_datetime(
    dfM_stg['time_event'], errors='coerce'
)

In [207]:
dfM_stg['KM'] = pd.to_numeric(
    dfM_stg['KM'], errors='coerce'
)

dfM_stg['delai_saisie_min'] = pd.to_numeric(
    dfM_stg['delai_saisie_min'], errors='coerce'
)

dfM_stg['delai_sai_even'] = pd.to_numeric(
    dfM_stg['delai_sai_even'], errors='coerce'
)

In [208]:
#pour la verfication si dfM_stg a etait remplier ou non 
print("Nombre de lignes :", len(dfM_stg))
print("Nombre de colonnes :", len(dfM_stg.columns))
print(dfM_stg.columns.tolist())

Nombre de lignes : 482470
Nombre de colonnes : 22
['voycle', 'chauff', 'camion', 'date_idb', 'name_event', 'date_saisi', 'KM', 'commentaire', 'client', 'next_destination', 'images', 'time_event', 'event_from', 'tempurature', 'SITE', 'voyage_str', 'nature_voyage', 'delai_saisie_min', 'categorie_remontee', 'delai_sai_even', 'time_event_manquante', 'camion_tms']

In [209]:
print(len(dfM_stg))

482470

In [210]:
#nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
"""
import pandas as pd
import numpy as np

# 1. Identifier toutes les colonnes numériques/décimales
num_cols = ['KM', 'delai_saisie_min', 'delai_sai_even']

for col in num_cols:
    if col in dfM_stg.columns:
        # Convertir en float, arrondir à 2 décimales, puis transformer en STRING
        dfM_stg[col] = pd.to_numeric(dfM_stg[col], errors='coerce').round(2)
        # Remplacer les NaN par None et convertir les nombres en texte (ex: "1500.50")
        dfM_stg[col] = dfM_stg[col].apply(lambda x: f"{x:.2f}" if pd.notnull(x) else None)

# 2. Nettoyage rapide des dates pour éviter les conflits datetime2
date_cols = ['date_idb', 'date_saisi', 'time_event']
for col in date_cols:
    if col in dfM_stg.columns:
        dfM_stg[col] = pd.to_datetime(dfM_stg[col], errors='coerce')
        dfM_stg[col] = dfM_stg[col].dt.strftime('%Y-%m-%d %H:%M:%S').where(dfM_stg[col].notnull(), None)

# 3. Préparer les enregistrements (remplacer NaN restants par None/NULL)
records = dfM_stg.where(pd.notnull(dfM_stg), None).values.tolist()

# 4. Insertion via PyODBC
raw_conn = engine.raw_connection()
cursor = raw_conn.cursor()

cursor.execute("TRUNCATE TABLE dbo.STG_Mobility_Events;")
raw_conn.commit()

cursor.fast_executemany = True

cols = ", ".join([f"[{col}]" for col in dfM_stg.columns])
placeholders = ", ".join(["?"] * len(dfM_stg.columns))
sql = f"INSERT INTO dbo.STG_Mobility_Events ({cols}) VALUES ({placeholders})"

try:
    cursor.executemany(sql, records)
    raw_conn.commit()
    print(f"✅ Mobility chargé avec succès : {len(dfM_stg)} lignes !")
except Exception as e:
    raw_conn.rollback()
    print("❌ Erreur lors de l'insertion :", e)
finally:
    cursor.close()
    raw_conn.close()
"""

'\nimport pandas as pd\nimport numpy as np\n\n# 1. Identifier toutes les colonnes numériques/décimales\nnum_cols = [\'KM\', \'delai_saisie_min\', \'delai_sai_even\']\n\nfor col in num_cols:\n    if col in dfM_stg.columns:\n        # Convertir en float, arrondir à 2 décimales, puis transformer en STRING\n        dfM_stg[col] = pd.to_numeric(dfM_stg[col], errors=\'coerce\').round(2)\n        # Remplacer les NaN par None et convertir les nombres en texte (ex: "1500.50")\n        dfM_stg[col] = dfM_stg[col].apply(lambda x: f"{x:.2f}" if pd.notnull(x) else None)\n\n# 2. Nettoyage rapide des dates pour éviter les conflits datetime2\ndate_cols = [\'date_idb\', \'date_saisi\', \'time_event\']\nfor col in date_cols:\n    if col in dfM_stg.columns:\n        dfM_stg[col] = pd.to_datetime(dfM_stg[col], errors=\'coerce\')\n        dfM_stg[col] = dfM_stg[col].dt.strftime(\'%Y-%m-%d %H:%M:%S\').where(dfM_stg[col].notnull(), None)\n\n# 3. Préparer les enregistrements (remplacer NaN restants par None/NULL)\nrecords = dfM_stg.where(pd.notnull(dfM_stg), None).values.tolist()\n\n# 4. Insertion via PyODBC\nraw_conn = engine.raw_connection()\ncursor = raw_conn.cursor()\n\ncursor.execute("TRUNCATE TABLE dbo.STG_Mobility_Events;")\nraw_conn.commit()\n\ncursor.fast_executemany = True\n\ncols = ", ".join([f"[{col}]" for col in dfM_stg.columns])\nplaceholders = ", ".join(["?"] * len(dfM_stg.columns))\nsql = f"INSERT INTO dbo.STG_Mobility_Events ({cols}) VALUES ({placeholders})"\n\ntry:\n    cursor.executemany(sql, records)\n    raw_conn.commit()\n    print(f"✅ Mobility chargé avec succès : {len(dfM_stg)} lignes !")\nexcept Exception as e:\n    raw_conn.rollback()\n    print("❌ Erreur lors de l\'insertion :", e)\nfinally:\n    cursor.close()\n    raw_conn.close()\n'

In [211]:
print(len(dfM_stg))

482470

In [212]:
dfUser_stg= df.copy()

In [213]:
#44444444444444444444444444444444444
"""
dfUser_stg.to_sql(
    name='STG_User_Mobility',
    con=engine,
    if_exists='append',
    index=False,
    chunksize=5000,
    method='multi'
)

print("User_Mobility chargé :", len(dfUser_stg), "lignes")
"""

'\ndfUser_stg.to_sql(\n    name=\'STG_User_Mobility\',\n    con=engine,\n    if_exists=\'append\',\n    index=False,\n    chunksize=5000,\n    method=\'multi\'\n)\n\nprint("User_Mobility chargé :", len(dfUser_stg), "lignes")\n'

In [214]:
dfChauffeur=df4.copy()

In [215]:
#88888888888888888888888888888888888888888888888888888

In [216]:
"""
dfChauffeur.to_sql(
    name='STG_Chauffeurs',
    con=engine,
    if_exists='append',
    index=False,
    chunksize=5000,
    method='multi'
)

print("Chauffeurs chargé :", len(dfChauffeur), "lignes")
"""

'\ndfChauffeur.to_sql(\n    name=\'STG_Chauffeurs\',\n    con=engine,\n    if_exists=\'append\',\n    index=False,\n    chunksize=5000,\n    method=\'multi\'\n)\n\nprint("Chauffeurs chargé :", len(dfChauffeur), "lignes")\n'

In [219]:
Fact_Voyage.shape

(86957, 21)

In [224]:
for col in Fact_Voyage.columns:
    print(col)

VOYCLE
date_depart
heure_depart
date_fin
heure_fin
id_chauffeur
nom_chauffeur
id_camion
capacite
site
site_chauffeur
site_camion
type_voyage
type_transport
nb_references
nb_evenements
nb_evenements_sans_temps
delai_saisie_moyen
present_mobility
voyage_sans_evenement
nb_anomalies

In [225]:
"""
try:
    Fact_Voyage.to_sql(
        name='STG_Fact_Voyage',
        con=engine,
        if_exists='append',  # Options : 'append' (ajouter), 'replace' (écraser/recréer), 'fail' (bloquer si existe)
        index=False,         # Ne pas insérer l'index pandas comme une colonne
        chunksize=1000       # Insertion par lots pour de meilleures performances
    )
    print("Chargement réussi dans SQL Server !")

except Exception as e:
    print(f"Erreur lors du chargement : {e}")
    """

C:\Users\nourg\anaconda3\Lib\site-packages\pandas\io\sql.py:1648: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

Chargement réussi dans SQL Server !